Repository openshift/compliance-operator, pull requests merged in 2019-12, with the labels that each got.

#42 Allow operator to watch nodes
  deploy/role.yaml
Labels: approved, lgtm, size/XS

#43 Add "generate" Makefile target
  Makefile
Labels: approved, lgtm, size/XS

#25 Build the operator as part of the image build
  build/Dockerfile
Labels: approved, lgtm, size/S

#35 Improve coverage of unit tests
  pkg/controller/compliancescan/compliancescan_controller_test.go
Labels: approved, lgtm, size/M

#40 Re-use same operator cluster to run e2e tests
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm, size/L

#45 Set podman as default runtime
  Makefile
Labels: approved, lgtm, size/XS

#39 Add compliance scan result to status
  deploy/crds/complianceoperator.compliance.openshift.io_compliancescans_crd.yaml
  pkg/apis/complianceoperator/v1alpha1/compliancescan_types.go
  pkg/apis/complianceoperator/v1alpha1/zz_generated.openapi.go
  pkg/controller/compliancescan/compliancescan_controller.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm, size/L

#46 Redirect output of `oc whoami`
  Makefile
Labels: approved, lgtm, size/XS

#52 Fix unit-test to be in the appropriate phase
  pkg/controller/compliancescan/compliancescan_controller_test.go
Labels: approved, lgtm, size/XS

#54 add GoLand files to .gitignore
  .gitignore
Labels: approved, lgtm, size/XS

#51 While in RUNNING state Return to LAUNCHING state if pod is mising
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/compliancescan_controller_test.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm, size/L

#56 Add ability to pass parameters to the e2e test run
  Makefile
Labels: approved, lgtm, size/XS

#57 schedule operator only on masters
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#53 Do Makefile `all` target only build the code
  Makefile
Labels: approved, lgtm, size/XS

#58 Make deepcopy of scan instance before passing it to the handlers
  pkg/controller/compliancescan/compliancescan_controller.go
Labels: approved, lgtm, size/S

#59 Two trivial patches
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm, size/S

#60 Prepare makefile for vendor directory usage
  Dockerfile.ci
  Makefile
  build/Dockerfile
Labels: approved, lgtm, size/S

#62 Up global go test timeout to 30 min
  Makefile
Labels: approved, lgtm, size/XS

#63 Unset GOFLAGS before operator-sdk call
  Makefile
Labels: approved, lgtm, size/XS

#64 Create e2e-local makefile target
  Makefile
Labels: approved, lgtm, size/XS

#66 Add missing permissions to make service monitor work
  deploy/role.yaml
Labels: approved, lgtm, size/S

#67 Add interface for non-retriable errors
  pkg/controller/common/errors.go
  pkg/controller/common/errors_suite_test.go
  pkg/controller/common/errors_test.go
  pkg/controller/complianceremediation/complianceremediation_controller.go
  pkg/controller/compliancesuite/compliancesuite_controller.go
Labels: approved, lgtm, size/L

#70 Two fixes in e2e tests so that we can fix our scanner image
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm, size/M

#71 E2E tests: Add tests for remediations
  pkg/controller/complianceremediation/complianceremediation_controller.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm, size/L
