Repository openshift/compliance-operator, pull requests merged in 2019-11, with the labels that each got.

#1 add a "push" Makefile target
  Makefile
Labels: lgtm, size/XS

#2 Change dependencies to use new repo path
  cmd/manager/main.go
  go.mod
  go.sum
  pkg/apis/addtoscheme_complianceoperator_v1alpha1.go
  pkg/apis/complianceoperator/v1alpha1/zz_generated.openapi.go
  pkg/controller/add_compliancescan.go
  pkg/controller/compliancescan/compliancescan_controller.go
Labels: size/S

#3 Use an init container to deliver the content
  deploy/crds/complianceoperator.compliance.openshift.io_compliancescans_crd.yaml
  deploy/crds/complianceoperator_v1alpha1_compliancescan_cr.yaml
  deploy/crds/complianceoperator_v1alpha1_compliancescan_crd.yaml
  pkg/apis/complianceoperator/v1alpha1/compliancescan_types.go
  pkg/apis/complianceoperator/v1alpha1/zz_generated.openapi.go
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/utils.go
Labels: lgtm, size/L

#4 Pass OPERATOR_NAME env variable when running operator locally
  Makefile
Labels: size/XS

#5 Apply go fmt to the code
  pkg/apis/complianceoperator/v1alpha1/compliancescan_types.go
Labels: size/S

#7 Remove unused function parameter
  pkg/controller/compliancescan/compliancescan_controller.go
Labels: lgtm, size/XS

#6 Make call to gofmt more compact by using `go fmt`
  Makefile
Labels: size/XS

#8 Add verify make target (which also runs gosec)
  Makefile
  go.mod
  go.sum
  tools.go
Labels: lgtm, size/M

#9 Add basic unit tests to compliancscan controler
  go.mod
  pkg/controller/compliancescan/compliancescan_controller_test.go
  pkg/controller/compliancescan/compliancescan_suite_test.go
Labels: size/M

#11 Run `go mod tidy` and upgrade ginkgo
  go.mod
  go.sum
Labels: size/S

#12 fix operator-sdk go.sum
  go.sum
Labels: size/XS

#10 Extend `clean` target to also clean go cache
  Makefile
Labels: size/S

#13 Add end to end tests
  Makefile
  deploy/role.yaml
  deploy/role_binding.yaml
  pkg/apis/complianceoperator/v1alpha1/compliancescan_types.go
  tests/e2e/main_test.go
  tests/e2e/single_scan_test.go
Labels: size/L

#14 operator-sdk make
  Makefile
Labels: size/S

#18 Update go.sum from operator-sdk test run
  go.sum
Labels: size/S

#19 Add OWNERS file
  OWNERS
Labels: size/XS

#20 Re-add gosec to tools.go
  go.mod
  go.sum
  tools.go
Labels: size/S

#23 Up e2e test timeout
  tests/e2e/single_scan_test.go
Labels: approved, lgtm, size/XS

#24 Switch operator build to use ubi 8 instead of 7
  build/Dockerfile
Labels: approved, lgtm, size/XS

#28 e2e tests: Be resilient to temporary unavailability of k8s
  tests/e2e/single_scan_test.go
Labels: approved, lgtm, size/XS

#27 Make wget call to get operator-sdk for non-verbose
  Makefile
Labels: approved, lgtm, size/XS

#26 Add Dockerfile specifically for CI
  Dockerfile.ci
Labels: approved, lgtm, size/S

#31 resilience: retry getting status until timeout regardless of errors
  tests/e2e/helpers.go
Labels: approved, lgtm, size/S

#30 Use go 1.12 for ocp/builder image
  Dockerfile.ci
Labels: approved, lgtm, size/XS

#33 Use golang.org's gosumdb and proxy
  Dockerfile.ci
Labels: approved, lgtm, size/XS

#34 Build CI dockerfile from explicit workdir point to our repo
  Dockerfile.ci
Labels: approved, lgtm, size/XS

#21 Use relevant images in e2e tests
  Makefile
Labels: approved, size/M

#32 Refactor e2e tests for readability
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm, size/L

#38 e2e: Add test for scan with unexistent profile
  tests/e2e/e2e_test.go
Labels: approved, lgtm, size/S

#37 Clean up Makefile and add help target
  Makefile
Labels: approved, lgtm, size/M

#36 e2e: Test ComplianceScan filtered with nodeSelector
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm, size/M
