Repository openshift/compliance-operator, pull requests merged in 2020-11, with the labels that each got.

#463 Hardening: Set some general hardening settings for our containers
  deploy/operator.yaml
  pkg/controller/compliancescan/aggregator.go
  pkg/controller/compliancescan/resultserver.go
  pkg/controller/compliancescan/scan.go
  pkg/controller/compliancesuite/suitererunner.go
  pkg/controller/profilebundle/profilebundle_controller.go
Labels: approved, lgtm

#473 Bug 1898819: Aggregator: Only parse ConfigMaps with results
  cmd/manager/aggregator.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#469 Add support for remediation patching
  pkg/apis/compliance/v1alpha1/complianceremediation_types.go
  pkg/controller/complianceremediation/complianceremediation_controller.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm

#482 e2e: A bunch of minor code cleanups
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm

#480 E2E: Only log containers explicitly if an env var is set
  tests/e2e/helpers.go
Labels: approved, lgtm

#477 Bug 1899479: Aggregator: Only parse ConfigMaps with results
  cmd/manager/aggregator.go
Labels: approved, bugzilla/invalid-bug, bugzilla/severity-medium, lgtm

#484 Don't mark scan pods as still running when there's a failure
  pkg/controller/compliancescan/compliancescan_controller.go
Labels: approved, lgtm

#470 Expose API resource collector errors as warnings
  Makefile
  cmd/manager/api-resource-collector.go
  cmd/manager/resultcollector.go
  cmd/manager/scap.go
  deploy/crds/compliance.openshift.io_compliancescans_crd.yaml
  deploy/crds/compliance.openshift.io_compliancesuites_crd.yaml
  doc/crds.md
  images/testcontent/broken-content.Dockerfile
  pkg/apis/compliance/v1alpha1/compliancescan_types.go
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/scan.go
  pkg/utils/resultconfigmap.go
  tests/data/ocp4-unexistent-resource.xml
  tests/e2e/constants.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm

#474 Limit parallelism in our go test invocation
  Makefile
Labels: approved, lgtm

#481 Improve e2e test logging
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm

#476 e2e/testUnapplyRemediation: Wait for MC to change before continuing
  pkg/controller/complianceremediation/complianceremediation_controller.go
  tests/e2e/helpers.go
Labels: approved, lgtm

#486 Release v0.1.20
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_compliancescans_crd.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_compliancesuites_crd.yaml
Labels: approved, lgtm

#487 Fixes necessary for etcd encryption remediation
  cmd/manager/aggregator.go
  deploy/role.yaml
Labels: approved, lgtm

#493 Sync the 4.6 branch with master
  Makefile
  cmd/manager/aggregator.go
  cmd/manager/api-resource-collector.go
  cmd/manager/resultcollector.go
  cmd/manager/scap.go
  deploy/crds/compliance.openshift.io_compliancescans_crd.yaml
  deploy/crds/compliance.openshift.io_compliancesuites_crd.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_compliancescans_crd.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_compliancesuites_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  doc/crds.md
  images/testcontent/broken-content.Dockerfile
  pkg/apis/compliance/v1alpha1/complianceremediation_types.go
  pkg/apis/compliance/v1alpha1/compliancescan_types.go
  pkg/controller/complianceremediation/complianceremediation_controller.go
  pkg/controller/compliancescan/aggregator.go
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/resultserver.go
  pkg/controller/compliancescan/scan.go
  pkg/controller/compliancesuite/suitererunner.go
  pkg/controller/profilebundle/profilebundle_controller.go
  pkg/utils/resultconfigmap.go
  tests/data/ocp4-unexistent-resource.xml
  tests/e2e/constants.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm

#494 Sync the release-4-6 branch with master
  Makefile
  cmd/manager/aggregator.go
  cmd/manager/api-resource-collector.go
  cmd/manager/resultcollector.go
  cmd/manager/scap.go
  deploy/crds/compliance.openshift.io_compliancescans_crd.yaml
  deploy/crds/compliance.openshift.io_compliancesuites_crd.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_compliancescans_crd.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_compliancesuites_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  doc/crds.md
  images/testcontent/broken-content.Dockerfile
  pkg/apis/compliance/v1alpha1/complianceremediation_types.go
  pkg/apis/compliance/v1alpha1/compliancescan_types.go
  pkg/controller/complianceremediation/complianceremediation_controller.go
  pkg/controller/compliancescan/aggregator.go
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/resultserver.go
  pkg/controller/compliancescan/scan.go
  pkg/controller/compliancesuite/suitererunner.go
  pkg/controller/profilebundle/profilebundle_controller.go
  pkg/utils/resultconfigmap.go
  tests/data/ocp4-unexistent-resource.xml
  tests/e2e/constants.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm

#489 logcollector: Rely on the Reader interface instead of opening the files
  cmd/manager/resultcollector.go
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/utils/resultconfigmap.go
Labels: approved, lgtm

#488 Fix getting openshift user when it's something else than kubeadmin
  Makefile
Labels: approved, lgtm

#495 scan: Include the exact openscap version in scanner output
  pkg/controller/compliancescan/config.go
Labels: approved, lgtm

#499 Allow the api-resource-collector to get clusterlogforwarder objects
  deploy/role.yaml
Labels: approved, lgtm

#505 tests: Get rid of init() in profileparser test
  pkg/profileparser/profileparser_suite_test.go
  pkg/profileparser/profileparser_test.go
Labels: approved, lgtm

#501 e2e test fixing
  Makefile
  tests/e2e/constants.go
  tests/e2e/helpers.go
Labels: approved, lgtm

#504 e2e: Make tests that run moderate profile serial
  tests/e2e/e2e_test.go
Labels: approved, lgtm

#508 Remove the replaces attribute from the CSV (4.6 backport)
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
Labels: approved

#502 profileparser: Use a parallel worker object type
  pkg/profileparser/profileparser.go
Labels: approved, lgtm

#498 Bug 1901760: Don't fail the scansettingbinding if the same OS product is used
  pkg/controller/scansettingbinding/scansettingbinding_controller.go
  pkg/controller/scansettingbinding/scansettingbinding_controller_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#507 Remove the replaces attribute from the CSV
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
Labels: approved

#509 Allow api-resource-collector to view api-priority related objects
  deploy/role.yaml
Labels: approved

#496 Add and fix relevant operator information in the CSV
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#490 make: Don't use cache when building the openscap image
  Makefile
Labels: approved, lgtm

#510 doc: Updating commands in README
  README.md
Labels: approved, lgtm

#500 api-resource-collector: Treat NotFound errors as non-fatal
  cmd/manager/scap.go
Labels: approved, lgtm
