Repository openshift/compliance-operator, pull requests merged in 2020-01, with the labels that each got.

#72 Consistently use constants across the codebase
  pkg/apis/machineconfiguration/v1/machineconfig_types.go
  pkg/controller/complianceremediation/complianceremediation_controller.go
  pkg/controller/compliancesuite/compliancesuite_controller.go
Labels: approved, lgtm, size/S

#73 make: Increase the test timeout to 60minutes
  Makefile
Labels: approved, lgtm, size/XS

#78 RBAC: Allow updates of MachineConfigs
  deploy/role.yaml
  pkg/controller/complianceremediation/complianceremediation_controller.go
  pkg/controller/compliancescan/compliancescan_controller.go
Labels: approved, lgtm, size/M

#77 Use a configMap as the script source for the openscap container, not the container's entrypoint
  Makefile
  images/openscap/Dockerfile
  images/openscap/Dockerfile.ci
  images/openscap/jhrozek-openscap-with-chroot-epel-8.repo
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/compliancescan_controller_test.go
  pkg/controller/compliancescan/config.go
  pkg/controller/compliancescan/utils.go
Labels: approved, lgtm, size/L

#79 Update README.md
  README.md
Labels: approved, lgtm, size/M

#82 Update README.md - fix the links to other repos
  README.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#75 tests: Add an e2e test that unselects a remediation
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm, size/L

#83 Move scapresults code into this repo
  Makefile
  cmd/resultscollector/main.go
  go.mod
  go.sum
  images/resultscollector/Dockerfile
  images/resultscollector/Dockerfile.ci
  vendor/github.com/cenkalti/backoff/v3/.gitignore
  vendor/github.com/cenkalti/backoff/v3/.travis.yml
  vendor/github.com/cenkalti/backoff/v3/LICENSE
  vendor/github.com/cenkalti/backoff/v3/README.md
  vendor/github.com/cenkalti/backoff/v3/backoff.go
  vendor/github.com/cenkalti/backoff/v3/context.go
  vendor/github.com/cenkalti/backoff/v3/exponential.go
  vendor/github.com/cenkalti/backoff/v3/go.mod
  vendor/github.com/cenkalti/backoff/v3/retry.go
  vendor/github.com/cenkalti/backoff/v3/ticker.go
  vendor/github.com/cenkalti/backoff/v3/timer.go
  vendor/github.com/cenkalti/backoff/v3/tries.go
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/k8s.io/code-generator/generate-internal-groups.sh
  vendor/modules.txt
Labels: approved, lgtm, size/XL

#81 Add csv for OLM installation
  deploy/olm-catalog/compliance-operator/0.1.0/compliance-operator.v0.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/0.1.0/complianceoperator.compliance.openshift.io_complianceremediations_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.0/complianceoperator.compliance.openshift.io_compliancescans_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.0/complianceoperator.compliance.openshift.io_compliancesuites_crd.yaml
  deploy/olm-catalog/compliance-operator/compliance-operator.package.yaml
  deploy/olm-catalog/csv-config.yaml
Labels: approved, lgtm, size/XL

#74 Use deep-compare when checking if all remediations for a scan are the same
  pkg/controller/compliancesuite/compliancesuite_controller.go
  pkg/controller/compliancesuite/compliancesuite_suite_test.go
  pkg/controller/compliancesuite/compliancesuite_test_controller.go
Labels: approved, lgtm, size/L

#87 fix make image-to-cluster
  Makefile
Labels: approved, lgtm, size/XS
