Repository openshift/compliance-operator, pull requests merged in 2020-04, with the labels that each got.

#203 Add a debug message when no nodes match a scan
  pkg/controller/compliancescan/compliancescan_controller.go
Labels: approved, lgtm

#205 Manually fix issues in ignition schema
  vendor/github.com/coreos/ignition/config/v2_2/types/schema.go
Labels: approved, lgtm

#204 Remove remediations from suite status
  deploy/crds/compliance.openshift.io_compliancesuites_crd.yaml
  pkg/apis/compliance/v1alpha1/compliancesuite_types.go
  pkg/apis/compliance/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/complianceremediation/complianceremediation_controller.go
  pkg/controller/compliancesuite/compliancesuite_controller.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm

#206 Fix operator image tagging
  Makefile
  deploy/operator.yaml
Labels: approved, lgtm

#207 Release v0.1.7
  deploy/olm-catalog/compliance-operator/0.1.7/compliance-operator.v0.1.7.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/0.1.7/compliance.openshift.io_complianceremediations_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.7/compliance.openshift.io_compliancescans_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.7/compliance.openshift.io_compliancesuites_crd.yaml
  deploy/olm-catalog/compliance-operator/compliance-operator.package.yaml
Labels: approved

#208 Release v0.1.8
  deploy/olm-catalog/compliance-operator/0.1.0/compliance-operator.v0.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/0.1.0/complianceoperator.compliance.openshift.io_complianceremediations_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.0/complianceoperator.compliance.openshift.io_compliancescans_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.0/complianceoperator.compliance.openshift.io_compliancesuites_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.1/compliance-operator.v0.1.1.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/0.1.1/complianceoperator.compliance.openshift.io_complianceremediations_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.1/complianceoperator.compliance.openshift.io_compliancescans_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.1/complianceoperator.compliance.openshift.io_compliancesuites_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.2/compliance-operator.v0.1.2.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/0.1.2/complianceoperator.compliance.openshift.io_complianceremediations_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.2/complianceoperator.compliance.openshift.io_compliancescans_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.2/complianceoperator.compliance.openshift.io_compliancesuites_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.3/complianceoperator.compliance.openshift.io_complianceremediations_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.3/complianceoperator.compliance.openshift.io_compliancescans_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.3/complianceoperator.compliance.openshift.io_compliancesuites_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.4/compliance-operator.v0.1.4.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/0.1.4/compliance.openshift.io_complianceremediations_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.4/compliance.openshift.io_compliancescans_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.4/compliance.openshift.io_compliancesuites_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.5/compliance-operator.v0.1.5.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/0.1.5/compliance.openshift.io_complianceremediations_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.5/compliance.openshift.io_compliancescans_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.5/compliance.openshift.io_compliancesuites_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.6/compliance-operator.v0.1.6.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/0.1.6/compliance.openshift.io_complianceremediations_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.6/compliance.openshift.io_compliancescans_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.6/compliance.openshift.io_compliancesuites_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.7/compliance-operator.v0.1.7.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/0.1.8/compliance-operator.v0.1.8.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/0.1.8/compliance.openshift.io_complianceremediations_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.8/compliance.openshift.io_compliancescans_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.8/compliance.openshift.io_compliancesuites_crd.yaml
  deploy/olm-catalog/compliance-operator/compliance-operator.package.yaml
Labels: approved, lgtm

#209 Use machine-config-operator's MergeMachineConfigs function
  pkg/controller/complianceremediation/complianceremediation_controller.go
Labels: approved, lgtm

#210 Remediations: Only update merged MC if remediation isn't there yet
  pkg/controller/complianceremediation/complianceremediation_controller.go
Labels: approved, lgtm

#213 Shorten remediation annotations in MachineConfig
  pkg/controller/complianceremediation/complianceremediation_controller.go
  pkg/controller/complianceremediation/complianceremediation_controller_test.go
  pkg/controller/compliancescan/aggregator.go
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/config.go
  pkg/controller/compliancescan/utils.go
  pkg/utils/nameutils.go
Labels: approved, lgtm

#214 Document how to extract ARF from PVs better
  README.md
  cmd/resultserver/main.go
Labels: approved, lgtm

#211 Add a new CR, a ComplianceCheckResult
  cmd/remediation-aggregator/main.go
  deploy/crds/compliance.openshift.io_compliancecheckresults_crd.yaml
  deploy/role.yaml
  pkg/apis/compliance/v1alpha1/compliancecheckresult_types.go
  pkg/apis/compliance/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/utils/parse_arf_result.go
  pkg/utils/parse_arf_result_test.go
  pkg/utils/remediation_diff.go
  pkg/utils/remediation_diff_test.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm

#219 add it reference to switch projects before deployment and assigned pr…
  README.md
Labels: approved, lgtm, ok-to-test

#220 Upgrade to operator-sdk v0.16.0
  Makefile
  go.mod
  go.sum
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
  vendor/github.com/operator-framework/operator-sdk/internal/scaffold/cmd.go
  vendor/github.com/operator-framework/operator-sdk/internal/scaffold/controller_kind.go
  vendor/github.com/operator-framework/operator-sdk/internal/scaffold/doc.go
  vendor/github.com/operator-framework/operator-sdk/internal/scaffold/entrypoint.go
  vendor/github.com/operator-framework/operator-sdk/internal/scaffold/go_mod.go
  vendor/github.com/operator-framework/operator-sdk/internal/scaffold/register.go
  vendor/github.com/operator-framework/operator-sdk/internal/scaffold/role.go
  vendor/github.com/operator-framework/operator-sdk/internal/scaffold/scaffold.go
  vendor/github.com/operator-framework/operator-sdk/internal/util/k8sutil/k8sutil.go
  vendor/github.com/operator-framework/operator-sdk/internal/util/projutil/project_util.go
  vendor/github.com/operator-framework/operator-sdk/pkg/k8sutil/k8sutil.go
  vendor/github.com/operator-framework/operator-sdk/pkg/kube-metrics/metrics.go
  vendor/github.com/operator-framework/operator-sdk/pkg/kube-metrics/store.go
  vendor/github.com/operator-framework/operator-sdk/pkg/kube-metrics/uclient.go
  vendor/github.com/operator-framework/operator-sdk/pkg/log/zap/flags.go
  vendor/github.com/operator-framework/operator-sdk/pkg/log/zap/logger.go
  vendor/github.com/operator-framework/operator-sdk/pkg/metrics/metrics.go
  vendor/github.com/operator-framework/operator-sdk/pkg/metrics/service-monitor.go
  vendor/github.com/operator-framework/operator-sdk/pkg/test/client.go
  vendor/github.com/operator-framework/operator-sdk/pkg/test/context.go
  vendor/github.com/operator-framework/operator-sdk/pkg/test/e2eutil/wait_util.go
  vendor/github.com/operator-framework/operator-sdk/pkg/test/framework.go
  vendor/github.com/operator-framework/operator-sdk/pkg/test/resource_creator.go
  vendor/github.com/operator-framework/operator-sdk/version/version.go
  vendor/modules.txt
Labels: approved, lgtm

#223 Enforce TLS1.2 and default ciphers between result components
  cmd/resultscollector/main.go
  cmd/resultserver/main.go
Labels: approved, lgtm

#221 Generic remediations round #1
  deploy/crds/compliance.openshift.io_complianceremediations_crd.yaml
  pkg/apis/compliance/v1alpha1/complianceremediation_types.go
  pkg/apis/compliance/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/complianceremediation/complianceremediation_controller.go
  pkg/controller/complianceremediation/complianceremediation_controller_test.go
  pkg/controller/compliancesuite/compliancesuite_controller.go
  pkg/utils/mcfgutils.go
  pkg/utils/parse_arf_result.go
  pkg/utils/parse_arf_result_test.go
  pkg/utils/remediation_diff.go
  pkg/utils/remediation_diff_test.go
  pkg/utils/remediationutils.go
  tests/e2e/e2e_test.go
Labels: approved

#231 Add status and severity labels to ComplianceCheckResult
  cmd/remediation-aggregator/main.go
  pkg/apis/compliance/v1alpha1/compliancecheckresult_types.go
Labels: approved, lgtm

#222 Replace conditional cleanup code with flag
  Makefile
  tests/e2e/helpers.go
Labels: approved, lgtm

#233 Use privileged scc instead of node-exporter
  deploy/role.yaml
  pkg/controller/compliancescan/scan.go
Labels: approved, lgtm

#235 Remove unnecessary update in createScanPods function
  pkg/controller/compliancescan/scan.go
Labels: approved, lgtm

#232 Add Tailoring support
  deploy/crds/compliance.openshift.io_compliancescans_crd.yaml
  deploy/crds/compliance.openshift.io_compliancesuites_crd.yaml
  pkg/apis/compliance/v1alpha1/compliancescan_types.go
  pkg/apis/compliance/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/common/errors.go
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/config.go
  pkg/controller/compliancescan/scan.go
  tests/e2e/e2e_test.go
Labels: approved, lgtm

#236 Run suites and scans with debug=true to get more logs
  tests/e2e/e2e_test.go
Labels: approved, lgtm

#234 Generic Remediations round #2
  deploy/crds/compliance.openshift.io_complianceremediations_crd.yaml
  pkg/apis/compliance/v1alpha1/complianceremediation_types.go
  pkg/controller/complianceremediation/complianceremediation_controller.go
  pkg/controller/compliancesuite/compliancesuite_controller.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm
