Repository openshift/compliance-operator, pull requests merged in 2020-03, with the labels that each got.

#134 Fix a typo in README.md
  README.md
Labels: approved, lgtm, ok-to-test

#131 e2e: Test for errormsg being set in the scan status
  tests/e2e/helpers.go
Labels: approved, lgtm, size/XS

#91 Prepare to unbundle
  cmd/remediation-aggregator/main.go
  pkg/apis/machineconfiguration/v1/machineconfig_types.go
  pkg/controller/complianceremediation/complianceremediation_controller.go
  tests/e2e/helpers.go
Labels: approved, lgtm, ok-to-test, size/S

#132 Optimization: Only parse DS XML once in the aggregator
  cmd/remediation-aggregator/main.go
  pkg/utils/parse_arf_result.go
  pkg/utils/parse_arf_result_test.go
Labels: approved, lgtm, size/M

#135 Add build directories to .dockerignore
  .dockerignore
Labels: approved, lgtm, size/XS

#136 e2e: Speed up the e2e tests by pausing the pool and creating a sub-pool
  cmd/remediation-aggregator/main.go
  pkg/apis/machineconfiguration/v1/register.go
  pkg/controller/compliancesuite/compliancesuite_controller.go
  pkg/utils/nodeutils.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm, size/XL

#138 Add services delete permission to role
  deploy/role.yaml
Labels: approved, lgtm, size/XS

#140 Make remediation-aggregator more resilient
  cmd/remediation-aggregator/main.go
  pkg/controller/compliancescan/compliancescan_controller.go
Labels: approved, lgtm, size/M

#139 Delete scan/logcollector pods & PKI secrets when the scan is done
  deploy/role.yaml
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/compliancescan_controller_test.go
  pkg/controller/compliancescan/utils.go
Labels: approved, lgtm, size/L

#145 Add `debug` flag to compliancescan
  deploy/crds/complianceoperator.compliance.openshift.io_compliancescans_crd.yaml
  deploy/crds/complianceoperator.compliance.openshift.io_compliancesuites_crd.yaml
  pkg/apis/complianceoperator/v1alpha1/compliancescan_types.go
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancesuite/compliancesuite_controller.go
Labels: approved, lgtm, size/M

#144 Get updated CRDs
  deploy/crds/complianceoperator.compliance.openshift.io_complianceremediations_crd.yaml
  deploy/crds/complianceoperator.compliance.openshift.io_compliancescans_crd.yaml
Labels: approved, lgtm, size/L

#149 legal: add Apache 2.0 license
  LICENSE
Labels: approved, lgtm, size/L

#146 Replace generate openapi command with crds
  Makefile
Labels: approved, lgtm, size/XS

#147 compliancescan: Make debug=true imply running openscap with --verbose INFO
  pkg/controller/compliancescan/config.go
Labels: approved, lgtm, size/S

#148 Update description of API types
  deploy/crds/complianceoperator.compliance.openshift.io_complianceremediations_crd.yaml
  deploy/crds/complianceoperator.compliance.openshift.io_compliancescans_crd.yaml
  deploy/crds/complianceoperator.compliance.openshift.io_compliancesuites_crd.yaml
  pkg/apis/complianceoperator/v1alpha1/complianceremediation_types.go
  pkg/apis/complianceoperator/v1alpha1/compliancescan_types.go
  pkg/apis/complianceoperator/v1alpha1/compliancesuite_types.go
Labels: approved, lgtm, size/L

#150 Remove `compress` flag from result collector
  cmd/resultscollector/main.go
Labels: approved, lgtm, size/S

#143 complianceremediation: Don't reuse loop variable
  pkg/controller/complianceremediation/complianceremediation_controller.go
  pkg/controller/complianceremediation/complianceremediation_controller_test.go
  pkg/controller/complianceremediation/complianceremediation_suite_test.go
Labels: approved, lgtm, size/L

#152 Make automation for releases
  Makefile
Labels: approved, lgtm, size/M

#153 Run make fmt
  cmd/manager/main.go
  pkg/controller/complianceremediation/complianceremediation_controller_test.go
  pkg/controller/compliancesuite/compliancesuite_controller.go
Labels: approved, lgtm, size/M

#151 Always prepend "/content/" to content path when using it
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/utils.go
Labels: approved, lgtm, size/S

#154 Release continued
  Makefile
  deploy/olm-catalog/compliance-operator/0.1.2/compliance-operator.v0.1.2.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/0.1.2/complianceoperator.compliance.openshift.io_complianceremediations_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.2/complianceoperator.compliance.openshift.io_compliancescans_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.2/complianceoperator.compliance.openshift.io_compliancesuites_crd.yaml
Labels: approved, lgtm, size/XXL

#156 Enable updating channel in package
  Makefile
Labels: approved, lgtm, size/XS

#155 Run `go fmt` when doing basic builds as well
  Makefile
Labels: approved, lgtm, size/XS

#158 Move scc role
  deploy/role.yaml
  deploy/role_binding.yaml
Labels: approved, lgtm, size/M

#159 Make: Add missing operator-sdk prereqs
  Makefile
Labels: approved, lgtm, size/XS

#160 Release v0.1.3
  deploy/olm-catalog/compliance-operator/0.1.3/compliance-operator.v0.1.3.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/0.1.3/complianceoperator.compliance.openshift.io_complianceremediations_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.3/complianceoperator.compliance.openshift.io_compliancescans_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.3/complianceoperator.compliance.openshift.io_compliancesuites_crd.yaml
  deploy/olm-catalog/compliance-operator/compliance-operator.package.yaml
Labels: approved, lgtm, size/XXL

#161 More release process enhancements
  Makefile
Labels: approved, lgtm, size/XS

#157 Refactor: move scan components to their own files
  pkg/controller/compliancescan/aggregator.go
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/pki.go
  pkg/controller/compliancescan/resultserver.go
  pkg/controller/compliancescan/scan.go
Labels: approved, lgtm, size/XXL

#162 Remove hardcoded namespace references where possible
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  pkg/controller/compliancescan/aggregator.go
Labels: approved, lgtm, size/XS

#163 Up default number of replicas
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#164 Shorten API group
  README.md
  cmd/resultscollector/main.go
  deploy/crds/compliance.openshift.io_complianceremediations_crd.yaml
  deploy/crds/compliance.openshift.io_compliancescans_crd.yaml
  deploy/crds/compliance.openshift.io_compliancesuites_crd.yaml
  deploy/crds/compliance.openshift.io_v1alpha1_complianceremediation_cr.yaml
  deploy/crds/compliance.openshift.io_v1alpha1_compliancescan_cr.yaml
  deploy/crds/compliance.openshift.io_v1alpha1_compliancesuite_cr.yaml
  deploy/role.yaml
  doc/remediation-flow.md
  pkg/apis/complianceoperator/v1alpha1/doc.go
  pkg/apis/complianceoperator/v1alpha1/register.go
Labels: approved, lgtm, size/M

#165 Surface complete scan status to suite
  pkg/controller/compliancesuite/compliancesuite_controller.go
Labels: approved, lgtm, size/XS

#166 Make csv target idempotent
  Makefile
Labels: approved, lgtm, size/XS

#168 Remove if statement in operator-sdk target
  Makefile
Labels: approved, lgtm, size/XS

#171 Use predictable names for pods and configmaps
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/compliancescan_controller_test.go
  pkg/controller/compliancescan/scan.go
Labels: approved, lgtm, size/M

#172 Release v0.1.4
  deploy/olm-catalog/compliance-operator/0.1.4/compliance-operator.v0.1.4.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/0.1.4/compliance.openshift.io_complianceremediations_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.4/compliance.openshift.io_compliancescans_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.4/compliance.openshift.io_compliancesuites_crd.yaml
  deploy/olm-catalog/compliance-operator/compliance-operator.package.yaml
Labels: approved, lgtm

#173 Change API groups to match our current scheme
  cmd/remediation-aggregator/main.go
  pkg/apis/addtoscheme_compliance_v1alpha1.go
  pkg/apis/compliance/group.go
  pkg/apis/compliance/v1alpha1/complianceremediation_types.go
  pkg/apis/compliance/v1alpha1/compliancescan_types.go
  pkg/apis/compliance/v1alpha1/compliancesuite_types.go
  pkg/apis/compliance/v1alpha1/doc.go
  pkg/apis/compliance/v1alpha1/register.go
  pkg/apis/compliance/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/complianceremediation/complianceremediation_controller.go
  pkg/controller/complianceremediation/complianceremediation_controller_test.go
  pkg/controller/compliancescan/aggregator.go
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/compliancescan_controller_test.go
  pkg/controller/compliancescan/config.go
  pkg/controller/compliancescan/pki.go
  pkg/controller/compliancescan/resultserver.go
  pkg/controller/compliancescan/scan.go
  pkg/controller/compliancescan/utils.go
  pkg/controller/compliancesuite/compliancesuite_controller.go
  pkg/controller/compliancesuite/compliancesuite_test_controller.go
  pkg/utils/parse_arf_result.go
  pkg/utils/parse_arf_result_test.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm

#175 Tag operator's manager image
  Makefile
Labels: approved, lgtm

#179 hardening: Make resultscollector use its own service account
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  pkg/controller/compliancescan/scan.go
Labels: approved, lgtm

#180 hardening: Make resultserver use default Service Account
  pkg/controller/compliancescan/resultserver.go
Labels: approved, lgtm

#181 hardening: Only mount volumes read/write where needed
  pkg/controller/compliancescan/aggregator.go
  pkg/controller/compliancescan/resultserver.go
  pkg/controller/compliancescan/scan.go
Labels: approved, lgtm

#176 Rename compliancesuite controller test
  pkg/controller/compliancesuite/compliancesuite_controller_test.go
Labels: approved, lgtm

#177 Remove volumeattachements from role
  deploy/role.yaml
Labels: approved, lgtm

#178 Enable JUnit output for unit tests
  Makefile
Labels: approved, lgtm

#183 Add Dockerfiles for openscap yaml-probe testing
  images/openscap/Dockerfile.maint-1.3
  images/openscap/mrogers-openscap-with-yaml-epel-8.repo
Labels: approved, lgtm

#174 Fix getting previous csv version
  Makefile
Labels: approved, lgtm

#182 hardening: Make remediation-aggregator use its own Service Account
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  pkg/controller/compliancescan/aggregator.go
Labels: approved, lgtm

#184 hardening: Drop usage of privileged scc and containers
  deploy/role.yaml
  pkg/controller/compliancescan/aggregator.go
  pkg/controller/compliancescan/scan.go
Labels: approved, lgtm

#186 Release v0.1.5
  deploy/olm-catalog/compliance-operator/0.1.5/compliance-operator.v0.1.5.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/0.1.5/compliance.openshift.io_complianceremediations_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.5/compliance.openshift.io_compliancescans_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.5/compliance.openshift.io_compliancesuites_crd.yaml
  deploy/olm-catalog/compliance-operator/compliance-operator.package.yaml
Labels: approved, lgtm

#187 Use quay.io/jhrozek/openscap-ocp:latest in the deployment
  deploy/operator.yaml
Labels: approved, lgtm

#191 Remove duplicate definition of diffRemediationList
  cmd/remediation-aggregator/main.go
  pkg/controller/compliancesuite/compliancesuite_controller.go
  pkg/controller/compliancesuite/compliancesuite_suite_test.go
  pkg/utils/remediation_diff.go
  pkg/utils/remediation_diff_test.go
Labels: approved, lgtm

#188 Implement remediation auto-apply
  cmd/manager/main.go
  deploy/role.yaml
  pkg/controller/complianceremediation/complianceremediation_controller.go
  pkg/controller/compliancesuite/compliancesuite_controller.go
  pkg/utils/nodeutils.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
  vendor/github.com/openshift/machine-config-operator/pkg/apis/machineconfiguration.openshift.io/install.go
  vendor/modules.txt
Labels: approved, lgtm

#190 Makefile: Use `oc apply` instead of `oc create`
  Makefile
Labels: approved, lgtm

#192 Do creator functions for wrapper-types
  pkg/apis/compliance/v1alpha1/compliancesuite_types.go
  pkg/controller/compliancesuite/compliancesuite_controller.go
Labels: approved, lgtm

#193 Remove usages of mco client
  pkg/controller/complianceremediation/complianceremediation_controller.go
  pkg/utils/remediation_diff.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
  vendor/github.com/openshift/machine-config-operator/pkg/generated/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/machine-config-operator/pkg/generated/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/machine-config-operator/pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/containerruntimeconfig.go
  vendor/github.com/openshift/machine-config-operator/pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/controllerconfig.go
  vendor/github.com/openshift/machine-config-operator/pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/doc.go
  vendor/github.com/openshift/machine-config-operator/pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/generated_expansion.go
  vendor/github.com/openshift/machine-config-operator/pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/kubeletconfig.go
  vendor/github.com/openshift/machine-config-operator/pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/machineconfig.go
  vendor/github.com/openshift/machine-config-operator/pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/machineconfigpool.go
  vendor/github.com/openshift/machine-config-operator/pkg/generated/clientset/versioned/typed/machineconfiguration.openshift.io/v1/machineconfiguration.openshift.io_client.go
  vendor/modules.txt
Labels: approved, lgtm

#194 Release v0.1.6
  deploy/olm-catalog/compliance-operator/0.1.6/compliance-operator.v0.1.6.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/0.1.6/compliance.openshift.io_complianceremediations_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.6/compliance.openshift.io_compliancescans_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.6/compliance.openshift.io_compliancesuites_crd.yaml
  deploy/olm-catalog/compliance-operator/compliance-operator.package.yaml
Labels: approved, lgtm

#196 Fix two issues with the example CR
  deploy/crds/compliance.openshift.io_v1alpha1_compliancesuite_cr.yaml
Labels: approved, lgtm

#198 Additional print columns
  deploy/crds/compliance.openshift.io_complianceremediations_crd.yaml
  deploy/crds/compliance.openshift.io_compliancescans_crd.yaml
  deploy/crds/compliance.openshift.io_compliancesuites_crd.yaml
  pkg/apis/compliance/v1alpha1/complianceremediation_types.go
  pkg/apis/compliance/v1alpha1/compliancescan_types.go
  pkg/apis/compliance/v1alpha1/compliancesuite_types.go
  pkg/controller/complianceremediation/complianceremediation_controller.go
  pkg/controller/complianceremediation/complianceremediation_controller_test.go
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/compliancescan_controller_test.go
  pkg/controller/compliancesuite/compliancesuite_controller.go
  pkg/utils/parse_arf_result.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm

#199 Improve operator logging
  pkg/controller/complianceremediation/complianceremediation_controller.go
  pkg/controller/compliancescan/aggregator.go
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/pki.go
  pkg/controller/compliancescan/resultserver.go
  pkg/controller/compliancescan/scan.go
  pkg/controller/compliancesuite/compliancesuite_controller.go
Labels: approved, lgtm
