Repository openshift/compliance-operator, pull requests merged in 2020-02, with the labels that each got.

#90 e2e: Check that the generation changed, not that it increased
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm, size/M

#86 Remove duplicate line
  go.sum
Labels: approved, lgtm, needs-ok-to-test, size/XS

#93 Temporarily use bzip2 to decompress configmaps
  go.mod
  go.sum
  pkg/controller/compliancescan/utils.go
  pkg/controller/compliancesuite/compliancesuite_controller.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
  vendor/github.com/dsnet/compress/.travis.yml
  vendor/github.com/dsnet/compress/LICENSE.md
  vendor/github.com/dsnet/compress/README.md
  vendor/github.com/dsnet/compress/api.go
  vendor/github.com/dsnet/compress/bzip2/bwt.go
  vendor/github.com/dsnet/compress/bzip2/common.go
  vendor/github.com/dsnet/compress/bzip2/fuzz_off.go
  vendor/github.com/dsnet/compress/bzip2/fuzz_on.go
  vendor/github.com/dsnet/compress/bzip2/internal/sais/common.go
  vendor/github.com/dsnet/compress/bzip2/internal/sais/sais_byte.go
  vendor/github.com/dsnet/compress/bzip2/internal/sais/sais_int.go
  vendor/github.com/dsnet/compress/bzip2/mtf_rle2.go
  vendor/github.com/dsnet/compress/bzip2/prefix.go
  vendor/github.com/dsnet/compress/bzip2/reader.go
  vendor/github.com/dsnet/compress/bzip2/rle1.go
  vendor/github.com/dsnet/compress/bzip2/writer.go
  vendor/github.com/dsnet/compress/go.mod
  vendor/github.com/dsnet/compress/go.sum
  vendor/github.com/dsnet/compress/internal/common.go
  vendor/github.com/dsnet/compress/internal/debug.go
  vendor/github.com/dsnet/compress/internal/errors/errors.go
  vendor/github.com/dsnet/compress/internal/gofuzz.go
  vendor/github.com/dsnet/compress/internal/prefix/debug.go
  vendor/github.com/dsnet/compress/internal/prefix/decoder.go
  vendor/github.com/dsnet/compress/internal/prefix/encoder.go
  vendor/github.com/dsnet/compress/internal/prefix/prefix.go
  vendor/github.com/dsnet/compress/internal/prefix/range.go
  vendor/github.com/dsnet/compress/internal/prefix/reader.go
  vendor/github.com/dsnet/compress/internal/prefix/wrap.go
  vendor/github.com/dsnet/compress/internal/prefix/writer.go
  vendor/github.com/dsnet/compress/internal/release.go
  vendor/github.com/dsnet/compress/zbench.sh
  vendor/github.com/dsnet/compress/zfuzz.sh
  vendor/github.com/dsnet/compress/zprof.sh
  vendor/github.com/dsnet/compress/ztest.sh
  vendor/modules.txt
Labels: approved, size/XXL

#97 Add AGGREGATING phase to complianceScan controller
  pkg/apis/complianceoperator/v1alpha1/compliancescan_types.go
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/compliancescan_controller_test.go
Labels: approved, size/S

#98 Ensure scanstatuses in compliancesuite is not nil
  pkg/controller/compliancesuite/compliancesuite_controller.go
Labels: approved, size/XS

#99 Several patches to fix our CI: wait for CMs to appear, check for node status, fix predicates
  Makefile
  pkg/controller/compliancesuite/compliancesuite_controller.go
  pkg/utils/parse_arf_result_test.go
  tests/e2e/constants.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm, size/L

#100 Port over bzip compression from the standalone scapresults repo
  cmd/resultscollector/main.go
Labels: approved, lgtm, size/S

#80 Update README.md
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#102 Up ARF parsing unit test timeout
  pkg/utils/parse_arf_result_test.go
Labels: approved, lgtm, size/XS

#101 Add toleration to pod spec so we can scan master nodes too
  pkg/controller/compliancescan/compliancescan_controller.go
Labels: approved, lgtm, size/XS

#103 Use nodeSelector instead of nodeName to schedule pod
  pkg/controller/compliancescan/compliancescan_controller.go
Labels: approved, lgtm, size/XS

#104 Create a PVC per scan
  deploy/role.yaml
  pkg/controller/compliancescan/compliancescan_controller.go
Labels: approved, lgtm, size/M

#106 Fix container builds
  Makefile
  images/resultscollector/Dockerfile
  images/resultscollector/Dockerfile.ci
Labels: approved, lgtm, size/XS

#107 Add `make publish` and OperatorSource file for OLM
  Makefile
  deploy/olm-catalog/compliance-operator/compliance-operator.package.yaml
  deploy/olm-catalog/operator-source.yaml
Labels: approved, lgtm, size/S

#108 ARF report server
  Makefile
  cmd/resultscollector/main.go
  cmd/resultserver/main.go
  deploy/operator.yaml
  deploy/role.yaml
  images/resultserver/Dockerfile
  images/resultserver/Dockerfile.ci
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/config.go
  pkg/controller/compliancescan/utils.go
Labels: approved, lgtm, size/L

#109 Change quay namespace from Makefile to use compliance-operator
  Makefile
Labels: approved, lgtm, size/XS

#110 Make push target push the rest of the images
  Makefile
Labels: approved, lgtm, size/XS

#111 Wait for ConfigMaps in compliancescan controller
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancesuite/compliancesuite_controller.go
Labels: approved, lgtm, size/M

#112 Test newly built workload images in e2e tests
  Makefile
  deploy/operator.yaml
Labels: approved, size/M

#114 Delete resultserver on DONE phase
  pkg/controller/compliancescan/compliancescan_controller.go
Labels: approved, lgtm, size/M

#115 resultcollector: Run ConfigMap upload and ARF upload in parallel
  cmd/resultscollector/main.go
Labels: approved, lgtm, size/M

#117 Fix remediation-aggregator Dockerfiles
  images/remediation-aggregator/Dockerfile
  images/remediation-aggregator/Dockerfile.ci
Labels: approved, lgtm, size/XS

#119 Fix environment variable from the result server
  pkg/controller/compliancescan/utils.go
Labels: approved, lgtm, size/XS

#120 Add permission to delete deployments
  deploy/role.yaml
Labels: approved, lgtm, size/XS

#118 remediation-aggregator image fixes
  Makefile
  deploy/operator.yaml
  pkg/controller/compliancescan/utils.go
Labels: approved, lgtm, size/S

#121 Delete cluster_role_binding.yaml file
  deploy/cluster_role_binding.yaml
Labels: approved, lgtm, size/S

#123 Two trivial fixes
  cmd/resultscollector/main.go
  pkg/controller/compliancesuite/compliancesuite_controller.go
  tests/e2e/helpers.go
Labels: approved, lgtm, size/XS

#122 Update the documentation
  README.md
  deploy/crds/complianceoperator.compliance.openshift.io_v1alpha1_compliancesuite_cr.yaml
Labels: approved, lgtm, size/L

#125 Fix olm-catalog template to point to right image
  deploy/olm-catalog/compliance-operator/0.1.0/compliance-operator.v0.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#127 Make minor OLM release and enhance publishing workflow
  Makefile
  deploy/olm-catalog/compliance-operator/0.1.1/compliance-operator.v0.1.1.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/0.1.1/complianceoperator.compliance.openshift.io_complianceremediations_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.1/complianceoperator.compliance.openshift.io_compliancescans_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.1/complianceoperator.compliance.openshift.io_compliancesuites_crd.yaml
Labels: approved, lgtm, size/XL

#126 Make `E2E_SKIP_CONTAINER_PUSH` use previsouly uploaded images
  Makefile
Labels: approved, lgtm, size/S

#129 Allow the restart of the scan/logcollector pod
  cmd/resultscollector/main.go
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/config.go
Labels: approved, lgtm, size/L

#130 Remove unused variable from getScanResult function
  pkg/controller/compliancescan/compliancescan_controller.go
Labels: approved, lgtm, size/XS
