Repository openshift/compliance-operator, pull requests merged in 2020-08, with the labels that each got.

#379 ScanSettingBindings: Use normal events when creating or updating scans
  pkg/controller/scansettingbinding/scansettingbinding_controller.go
Labels: approved, lgtm

#378 Upgrade to operator-sdk v0.18.2
  Makefile
  go.mod
  go.sum
  vendor/github.com/operator-framework/operator-sdk/internal/scaffold/go_mod.go
  vendor/github.com/operator-framework/operator-sdk/version/version.go
  vendor/modules.txt
Labels: approved, lgtm

#381 Move CM creation to launching phase
  pkg/controller/compliancescan/compliancescan_controller.go
Labels: approved, lgtm

#382 images: Use a fallback RELATED_IMAGE_OPENSCAP value that actually works
  pkg/utils/images.go
Labels: approved, lgtm

#383 CSV: Fix typo in operator description
  deploy/olm-catalog/compliance-operator/0.1.12/compliance-operator.v0.1.12.clusterserviceversion.yaml
Labels: approved, lgtm

#377 Remediations: Set default state
  deploy/crds/compliance.openshift.io_complianceremediations_crd.yaml
  pkg/apis/compliance/v1alpha1/complianceremediation_types.go
Labels: approved, lgtm

#380 readme: Document the inconsistent state
  README.md
  pkg/apis/compliance/v1alpha1/compliancecheckresult_types.go
Labels: approved, lgtm

#386 Unify log tags for controllers
  pkg/controller/profilebundle/profilebundle_controller.go
  pkg/controller/scansettingbinding/scansettingbinding_controller.go
  pkg/controller/tailoredprofile/tailoredprofile_controller.go
Labels: approved, lgtm

#385 Make profileparser use its own service account
  deploy/crds/compliance.openshift.io_profiles_crd.yaml
  deploy/crds/compliance.openshift.io_rules_crd.yaml
  deploy/crds/compliance.openshift.io_variables_crd.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  pkg/apis/compliance/v1alpha1/compliancecheckresult_types.go
  pkg/apis/compliance/v1alpha1/profile_types.go
  pkg/apis/compliance/v1alpha1/rule_types.go
  pkg/apis/compliance/v1alpha1/variable_types.go
  pkg/controller/profilebundle/profilebundle_controller.go
Labels: approved, lgtm

#390 Deprecate Type field from ComplianceRemediation object
  pkg/apis/compliance/v1alpha1/complianceremediation_types.go
  pkg/utils/parse_arf_result.go
  pkg/utils/remediation_diff_test.go
Labels: approved, lgtm

#391 Deprecate MachineConfig-specific remediations
  deploy/crds/compliance.openshift.io_complianceremediations_crd.yaml
  pkg/apis/compliance/v1alpha1/complianceremediation_types.go
  pkg/apis/compliance/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/complianceremediation/complianceremediation_controller.go
Labels: approved, lgtm

#389 Create one reference ScanSettings object by default
  cmd/manager/operator.go
Labels: approved, lgtm

#399 Fix race condition in log collector
  cmd/manager/resultcollector.go
Labels: approved, lgtm

#397 Don't crash the api-resource-collector if no checks are found
  cmd/manager/scap.go
Labels: approved, lgtm

#393 Ignore deploy/ directory when building the container
  .dockerignore
Labels: approved, lgtm

#392 profileparser: Close XML file when run has ended
  cmd/manager/profileparser.go
  pkg/profileparser/profileparser.go
Labels: approved, lgtm

#400 Don't shadow an import
  cmd/manager/scap.go
Labels: approved, lgtm

#398 Don't touch other profiles when updating one profile
  pkg/profileparser/profileparser.go
  pkg/profileparser/profileparser_test.go
Labels: approved, lgtm

#395 Add note about OS support
  README.md
Labels: approved, lgtm

#396 Clean up suite-rerunner pods if suite is deleted
  deploy/role.yaml
  pkg/apis/compliance/v1alpha1/compliancesuite_types.go
  pkg/controller/compliancesuite/compliancesuite_controller.go
  pkg/controller/compliancesuite/suitererunner.go
Labels: approved, lgtm

#401 readme: Document that just deleting the namespace might not process finalizers
  README.md
Labels: approved, lgtm

#402 Enable Compliance Operator development on macOS
  Makefile
  build/Dockerfile
  cmd/manager/resultserver.go
  pkg/utils/directory.go
  pkg/utils/directory_darwin.go
  pkg/utils/directory_linux.go
Labels: approved, lgtm

#388 Add a troubleshooting document
  README.md
  cmd/manager/aggregator.go
  cmd/manager/resultcollector.go
  deploy/olm-catalog/compliance-operator/0.1.8/compliance-operator.v0.1.8.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/0.1.9/compliance-operator.v0.1.9.clusterserviceversion.yaml
  doc/remediation-flow.md
  doc/troubleshooting.md
  pkg/apis/compliance/v1alpha1/complianceremediation_types.go
  pkg/apis/compliance/v1alpha1/compliancescan_types.go
  pkg/controller/complianceremediation/complianceremediation_controller.go
  pkg/controller/complianceremediation/complianceremediation_controller_test.go
  pkg/controller/compliancescan/aggregator.go
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/config.go
  pkg/controller/compliancescan/rawresults.go
  pkg/controller/compliancescan/resultserver.go
  pkg/controller/compliancescan/scan.go
  pkg/controller/compliancesuite/compliancesuite_controller.go
  tests/e2e/helpers.go
Labels: approved, lgtm

#406 Release v0.1.13
  deploy/olm-catalog/compliance-operator/0.1.13/compliance-operator.v0.1.13.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/0.1.13/compliance.openshift.io_compliancecheckresults_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.13/compliance.openshift.io_complianceremediations_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.13/compliance.openshift.io_compliancescans_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.13/compliance.openshift.io_compliancesuites_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.13/compliance.openshift.io_profilebundles_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.13/compliance.openshift.io_profiles_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.13/compliance.openshift.io_rules_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.13/compliance.openshift.io_scansettingbindings_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.13/compliance.openshift.io_scansettings_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.13/compliance.openshift.io_tailoredprofiles_crd.yaml
  deploy/olm-catalog/compliance-operator/0.1.13/compliance.openshift.io_variables_crd.yaml
  deploy/olm-catalog/compliance-operator/compliance-operator.package.yaml
Labels: approved, lgtm

#394 Detect if scan is unschedulable
  cmd/manager/aggregator.go
  cmd/manager/resultcollector.go
  pkg/controller/common/constants.go
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/scan.go
  pkg/controller/compliancescan/utils.go
  pkg/profileparser/profileparser_test.go
  pkg/utils/resultconfigmap.go
  tests/e2e/e2e_test.go
Labels: approved, lgtm

#404 Make access modes and storage class configurable for PVs
  README.md
  deploy/crds/compliance.openshift.io_compliancescans_crd.yaml
  deploy/crds/compliance.openshift.io_compliancesuites_crd.yaml
  deploy/crds/compliance.openshift.io_scansettings_crd.yaml
  pkg/apis/compliance/v1alpha1/compliancescan_types.go
  pkg/apis/compliance/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/compliancescan_controller_test.go
  pkg/controller/compliancescan/rawresults.go
Labels: approved, lgtm

#407 Simplify README
  README.md
  deploy/crds/compliance.openshift.io_v1alpha1_scansettingbinding_cr.yaml
  doc/crds.md
Labels: approved, lgtm

#403 Permit creating remediations from a ComplianceScan
  README.md
  pkg/apis/compliance/v1alpha1/complianceremediation_types.go
  tests/e2e/e2e_test.go
Labels: approved, lgtm

#405 Rename aggregatedPhase and aggregatedResult to just Phase and Result
  deploy/crds/compliance.openshift.io_compliancesuites_crd.yaml
  doc/crds.md
  doc/remediation-flow.md
  pkg/apis/compliance/v1alpha1/compliancesuite_types.go
  pkg/controller/compliancesuite/compliancesuite_controller.go
  tests/e2e/helpers.go
Labels: approved

#409 Operator deployment: Change replicas to only deploy one
  deploy/operator.yaml
Labels: approved, lgtm

#408 doc: Improve the documentation of the Platform and Node scans, add a Platform scan CR
  README.md
  deploy/crds/compliance.openshift.io_v1alpha1_compliancescan_node_cr.yaml
  deploy/crds/compliance.openshift.io_v1alpha1_compliancescan_platform_cr.yaml
  deploy/crds/compliance.openshift.io_v1alpha1_compliancesuite_cr.yaml
Labels: approved, lgtm

#414 Fix memory leak in profileparser
  pkg/profileparser/profileparser.go
  pkg/profileparser/profileparser_test.go
Labels: approved, lgtm

#412 Workaround: Only use profileparser as an init container
  cmd/manager/pause.go
  cmd/manager/profileparser.go
  pkg/controller/profilebundle/profilebundle_controller.go
Labels: approved, lgtm

#413 Also push to latest when doing a release
  Makefile
Labels: approved, lgtm

#417 Bug 1873070: Only print error from standard parser if there's actually an error
  pkg/profileparser/profileparser.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#329 Remove divergence in content in testcontent image
  images/testcontent/Dockerfile.ci
Labels: approved, lgtm

#420 Remove operator source sample
  deploy/olm-catalog/operator-source.yaml
Labels: approved, lgtm

#421 Only compare Machineconfig spec, not the metadata
  pkg/controller/complianceremediation/complianceremediation_controller.go
Labels: approved, lgtm

#422 Update base images of our container files
  Dockerfile.ci
  Dockerfile.ocp
  images/openscap/Dockerfile.ci
Labels: approved, lgtm

#419 utils: Don't use ctime but mtime instead
  cmd/manager/resultserver_test.go
  pkg/utils/directory_darwin.go
  pkg/utils/directory_linux.go
Labels: approved, lgtm
