Repository openshift/compliance-operator, pull requests merged in 2020-12, with the labels that each got.

#511 Bug 1902249: Fix tailored Platform scans
  cmd/manager/api-resource-collector.go
  cmd/manager/scap.go
  cmd/manager/scap_test.go
  pkg/controller/compliancescan/config.go
  pkg/controller/compliancescan/scan.go
  tests/e2e/e2e_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#514 Release v0.1.22
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
Labels: approved

#517 use skipRange instead of replaces
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#518 Use skipRange in upstream release
  Makefile
Labels: approved

#515 Revert "remove .dockerignore file"
  .dockerignore
Labels: approved, lgtm

#520 sync the release-4.6 branch with master
  .dockerignore
  Makefile
  README.md
  cmd/manager/api-resource-collector.go
  cmd/manager/resultcollector.go
  cmd/manager/scap.go
  cmd/manager/scap_test.go
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/config.go
  pkg/controller/compliancescan/scan.go
  pkg/controller/scansettingbinding/scansettingbinding_controller.go
  pkg/controller/scansettingbinding/scansettingbinding_controller_test.go
  pkg/profileparser/profileparser.go
  pkg/profileparser/profileparser_suite_test.go
  pkg/profileparser/profileparser_test.go
  pkg/utils/resultconfigmap.go
  tests/e2e/constants.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved

#519 sync the rhaos-4.6 branch with master
  .dockerignore
  Makefile
  README.md
  cmd/manager/api-resource-collector.go
  cmd/manager/resultcollector.go
  cmd/manager/scap.go
  cmd/manager/scap_test.go
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/config.go
  pkg/controller/compliancescan/scan.go
  pkg/controller/scansettingbinding/scansettingbinding_controller.go
  pkg/controller/scansettingbinding/scansettingbinding_controller_test.go
  pkg/profileparser/profileparser.go
  pkg/profileparser/profileparser_suite_test.go
  pkg/profileparser/profileparser_test.go
  pkg/utils/resultconfigmap.go
  tests/e2e/constants.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved

#522 Funky fresh MCs
  pkg/controller/complianceremediation/complianceremediation_controller.go
Labels: approved, lgtm

#521 Only use latest tag when releasing the index image
  Makefile
Labels: approved, lgtm

#523 Add Xiaojie and Prashant as approvers
  OWNERS
Labels: approved, lgtm

#516 Update OPM version and use overwrite-latest option
  Makefile
Labels: approved

#526 Track imagestream when using `deploy-local` target
  Makefile
Labels: approved, lgtm

#527 Bug 1907410: Divide and Conquer (MachineConfigs)
  cmd/manager/aggregator.go
  pkg/apis/compliance/v1alpha1/complianceremediation_types.go
  pkg/controller/complianceremediation/complianceremediation_controller.go
  pkg/controller/complianceremediation/complianceremediation_controller_test.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#528 feat: add role to api-resource-collector for CIS Benchmark for OpenShift
  deploy/role.yaml
Labels: approved, lgtm, ok-to-test

#529 e2e/refactor: Use assertions instead of checking for errors everywhere
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm

#530 Release v0.1.23
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#531 only push index to latest tag
  Makefile
Labels: approved

#533 e2e/resiliency: Retry when trying to create subpool
  tests/e2e/constants.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm

#532 Bug 1909120: Always update default profilebundles on operator startup
  cmd/manager/operator.go
  tests/e2e/e2e_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#534 Bug 1908990: Remove non-namespaced deployments
  pkg/controller/profilebundle/profilebundle_controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
