Repository openshift/compliance-operator, pull requests merged in 2020-09, with the labels that each got.

#423 make: Don't use COURIER_PACKAGE_VERSION anymore
  Makefile
Labels: approved, lgtm

#425 Rename openscap-ocp container to just `scanner`
  doc/troubleshooting.md
  pkg/controller/compliancescan/compliancescan_controller.go
  tests/e2e/helpers.go
Labels: approved, lgtm

#424 Normalize the usage of labels to identify components in the operator
  doc/troubleshooting.md
  pkg/controller/compliancescan/aggregator.go
  pkg/controller/compliancescan/resultserver.go
  pkg/controller/compliancescan/scan.go
  pkg/controller/compliancesuite/suitererunner.go
  pkg/controller/profilebundle/profilebundle_controller.go
Labels: approved, lgtm

#426 MachineConfig: Use generation to check if we have an up-to-date remediation
  pkg/controller/complianceremediation/complianceremediation_controller.go
Labels: approved, lgtm

#429 e2e: Enable TestInconsistentResult for clusters with 2 worker nodes only
  tests/e2e/e2e_test.go
Labels: approved, lgtm

#431 Release v0.1.15
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#432 readme: Document how to install packages
  README.md
Labels: approved, lgtm

#433 Add descriptions for remediation keys
  deploy/crds/compliance.openshift.io_complianceremediations_crd.yaml
  pkg/apis/compliance/v1alpha1/complianceremediation_types.go
Labels: approved, lgtm

#435 Add icon to CSV
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#436 Bug 1862453: Also delete jobs when deleting compliancesuites
  deploy/role.yaml
  pkg/controller/compliancesuite/compliancesuite_controller.go
  pkg/controller/compliancesuite/suitererunner.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#437 ProfileBundles: Better ImageStream support and more tests
  pkg/controller/profilebundle/profilebundle_controller.go
  tests/e2e/e2e_test.go
  vendor/github.com/openshift/library-go/pkg/image/internal/digest/digest.go
  vendor/github.com/openshift/library-go/pkg/image/internal/digest/digester.go
  vendor/github.com/openshift/library-go/pkg/image/internal/digest/doc.go
  vendor/github.com/openshift/library-go/pkg/image/internal/reference/doc.go
  vendor/github.com/openshift/library-go/pkg/image/internal/reference/reference.go
  vendor/github.com/openshift/library-go/pkg/image/internal/reference/regexp.go
  vendor/github.com/openshift/library-go/pkg/image/reference/reference.go
  vendor/modules.txt
Labels: approved, lgtm

#442 Remove dupliace icon key in CSV
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#438 Bug 1877807: Support disconnected installs
  deploy/crds/compliance.openshift.io_compliancescans_crd.yaml
  deploy/crds/compliance.openshift.io_compliancesuites_crd.yaml
  deploy/crds/compliance.openshift.io_scansettings_crd.yaml
  pkg/apis/compliance/v1alpha1/compliancescan_types.go
  pkg/controller/compliancescan/config.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#443 Stop using operator-sdk build to build operator image
  Makefile
Labels: approved, lgtm

#444 Release v0.1.16
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_complianceremediations_crd.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_compliancescans_crd.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_compliancesuites_crd.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_scansettings_crd.yaml
Labels: approved, lgtm

#447 Prepend "test" before test flags to work with golang 1.15
  Makefile
Labels: approved, lgtm

#445 Two minor portability fixes
  Makefile
Labels: approved, lgtm

#450 Bug 1878163: Updating Dockerfile.rhel baseimages to mach ocp-build-data config
  Dockerfile.ci
  Dockerfile.ocp
  build/Dockerfile
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#449 Change aggregator's container name to something more fitting
  pkg/controller/compliancescan/aggregator.go
Labels: approved, lgtm

#448 Fix logging issues in scansettingbindings controller
  pkg/controller/scansettingbinding/scansettingbinding_controller.go
Labels: approved, lgtm

#446 Handle result events generically
  pkg/controller/common/events.go
  pkg/controller/compliancesuite/compliancesuite_controller.go
  pkg/controller/scansettingbinding/scansettingbinding_controller.go
Labels: approved, lgtm

#451 ProfileBundle: Add contentfile to server side printing parameters
  deploy/crds/compliance.openshift.io_profilebundles_crd.yaml
  pkg/apis/compliance/v1alpha1/profilebundle_types.go
Labels: approved, lgtm

#452 expose GOFLAGS from Makefile
  Makefile
Labels: approved, lgtm

#453 Fix race between the aggregator and operator in processing result configMaps
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/scan.go
Labels: approved, lgtm

#454 Release v0.1.17
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_profilebundles_crd.yaml
Labels: approved, lgtm

#456 make: Remove misleading comment
  Makefile
Labels: approved, lgtm
