Repository openshift/compliance-operator, pull requests merged in 2020-05, with the labels that each got.

#238 Use official complianceascode content image
  deploy/crds/compliance.openshift.io_v1alpha1_compliancesuite_cr.yaml
  deploy/olm-catalog/compliance-operator/0.1.8/compliance-operator.v0.1.8.clusterserviceversion.yaml
  pkg/controller/compliancescan/utils.go
Labels: approved, lgtm, ok-to-test

#239 e2e: Use content images from quay.io/complianceascode in tests as well
  tests/e2e/e2e_test.go
Labels: approved

#242 use golang 1.13 images for CI
  Dockerfile.ci
  images/remediation-aggregator/Dockerfile.ci
  images/resultscollector/Dockerfile.ci
  images/resultserver/Dockerfile.ci
Labels: approved

#241 make: Fix make run after upgrade to operator-sdk 1.17
  Makefile
Labels: approved, lgtm

#240 Implement re-scanning
  cmd/remediation-aggregator/main.go
  cmd/resultscollector/main.go
  cmd/resultserver/main.go
  deploy/crds/compliance.openshift.io_compliancescans_crd.yaml
  deploy/crds/compliance.openshift.io_compliancesuites_crd.yaml
  deploy/role.yaml
  pkg/apis/compliance/v1alpha1/compliancescan_types.go
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/resultserver.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm

#212 Enable OCP API scanning
  Makefile
  cmd/api-resource-collector/log.go
  cmd/api-resource-collector/main.go
  cmd/api-resource-collector/scap.go
  cmd/api-resource-collector/scap_test.go
  deploy/crds/compliance.openshift.io_compliancescans_crd.yaml
  deploy/crds/compliance.openshift.io_compliancesuites_crd.yaml
  deploy/operator.yaml
  deploy/role_binding.yaml
  go.mod
  images/api-resource-collector/Dockerfile
  images/api-resource-collector/Dockerfile.ci
  pkg/apis/compliance/v1alpha1/compliancescan_types.go
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/compliancescan_controller_test.go
  pkg/controller/compliancescan/config.go
  pkg/controller/compliancescan/scan.go
  pkg/controller/compliancescan/utils.go
  tests/data/ssg-ocp4-ds-new.xml
  tests/e2e/e2e_test.go
Labels: approved

#243 Stop relying on annotations for aggregator pod
  pkg/controller/compliancescan/aggregator.go
  pkg/controller/compliancescan/compliancescan_controller.go
Labels: approved, lgtm

#244 Generate events to be read by RHACM
  deploy/role.yaml
  pkg/apis/compliance/v1alpha1/compliancesuite_types.go
  pkg/controller/common/constants.go
  pkg/controller/compliancesuite/compliancesuite_controller.go
Labels: approved, lgtm

#246 Introduce scheduled scans
  Makefile
  cmd/manager/common.go
  cmd/manager/main.go
  cmd/manager/operator.go
  cmd/manager/suitererunner.go
  cmd/remediation-aggregator/main.go
  deploy/crds/compliance.openshift.io_compliancescans_crd.yaml
  deploy/crds/compliance.openshift.io_compliancesuites_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  go.mod
  go.sum
  pkg/apis/compliance/v1alpha1/complianceremediation_types.go
  pkg/apis/compliance/v1alpha1/compliancesuite_types.go
  pkg/controller/compliancescan/aggregator.go
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/resultserver.go
  pkg/controller/compliancescan/scan.go
  pkg/controller/compliancescan/utils.go
  pkg/controller/compliancesuite/compliancesuite_controller.go
  pkg/controller/compliancesuite/suitererunner.go
  pkg/utils/images.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
  vendor/github.com/robfig/cron/.gitignore
  vendor/github.com/robfig/cron/.travis.yml
  vendor/github.com/robfig/cron/LICENSE
  vendor/github.com/robfig/cron/README.md
  vendor/github.com/robfig/cron/constantdelay.go
  vendor/github.com/robfig/cron/cron.go
  vendor/github.com/robfig/cron/doc.go
  vendor/github.com/robfig/cron/parser.go
  vendor/github.com/robfig/cron/spec.go
  vendor/modules.txt
Labels: approved, lgtm

#247 Makefile: Add E2E_SKIP_CONTAINER_BUILD for local e2e
  Makefile
Labels: approved, lgtm

#250 make: Add a flag to enable make run again
  Makefile
Labels: approved

#249 Resilience: retry updating scans in rerunner
  cmd/manager/suitererunner.go
Labels: approved, lgtm

#251 Surface validation error to ComplianceSuite object
  deploy/crds/compliance.openshift.io_compliancesuites_crd.yaml
  pkg/apis/compliance/v1alpha1/compliancesuite_types.go
  pkg/controller/compliancesuite/compliancesuite_controller.go
  pkg/controller/compliancesuite/suitererunner.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm

#245 Platform scan follow-ups
  Makefile
  cmd/api-resource-collector/scap.go
  deploy/operator.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  images/api-resource-collector/Dockerfile.ci
  images/openscap/Dockerfile.maint-1.3
  pkg/controller/compliancescan/scan.go
  tests/e2e/e2e_test.go
Labels: approved

#248 Update docs to include latest changes
  .dockerignore
  README.md
  deploy/crds/compliance.openshift.io_v1alpha1_compliancesuite_cr.yaml
  doc/remediation-flow.md
Labels: approved

#252 Update remediation example
  deploy/crds/compliance.openshift.io_v1alpha1_complianceremediation_cr.yaml
Labels: approved

#253 Use explicit roles/clusterroles for api-resource-collector
  deploy/role.yaml
  deploy/role_binding.yaml
Labels: approved, lgtm

#254 Add api-resource-collector image to release
  Makefile
Labels: approved

#256 Add friendly rule name as annotation to check result
  cmd/remediation-aggregator/main.go
  pkg/apis/compliance/v1alpha1/compliancecheckresult_types.go
Labels: approved, lgtm

#260 Make PKI elements to be in the same namespace as the ComplianceScan
  pkg/controller/compliancescan/pki.go
Labels: approved, lgtm

#261 make: Default to openscap-ocp:1.3.3 tag when replacing paths
  Makefile
Labels: approved, lgtm

#263 aggregator: tidy up getCheckResultAnnotations()
  cmd/remediation-aggregator/main.go
Labels: approved

#262 e2e: Make sure ComplianceCheckResult has the expected labels
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved

#264 Replace reference to well-known label with kubernetes provided variable
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/scan.go
Labels: approved, lgtm
