Repository openshift/compliance-operator, pull requests merged in 2021-09, with the labels that each got.

#693 Associate variable with compliance check result
  cmd/manager/aggregator.go
  deploy/crds/compliance.openshift.io_compliancecheckresults_crd.yaml
  doc/crds.md
  pkg/apis/compliance/v1alpha1/compliancecheckresult_types.go
  pkg/apis/compliance/v1alpha1/zz_generated.deepcopy.go
  pkg/utils/parse_arf_result.go
  pkg/utils/parse_arf_result_test.go
Labels: approved, lgtm, ok-to-test

#691 Enable Creation of TailoredProfiles without extending existing ones
  deploy/crds/compliance.openshift.io_tailoredprofiles_crd.yaml
  doc/crds.md
  pkg/apis/compliance/v1alpha1/tailoredprofile_types.go
  pkg/controller/scansettingbinding/scansettingbinding_controller.go
  pkg/controller/scansettingbinding/scansettingbinding_controller_test.go
  pkg/controller/tailoredprofile/tailoredprofile_controller.go
  pkg/controller/tailoredprofile/tailoredprofile_controller_test.go
  pkg/xccdf/tailoring.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm

#697 e2e: Migrate TestScanProducesRemediations to use ScanSettingBinding
  tests/e2e/e2e_test.go
Labels: approved, lgtm

#687 Make default scanTolerations more tolerant
  deploy/crds/compliance.openshift.io_compliancescans_crd.yaml
  deploy/crds/compliance.openshift.io_compliancesuites_crd.yaml
  deploy/crds/compliance.openshift.io_scansettings_crd.yaml
  pkg/apis/compliance/v1alpha1/compliancescan_types.go
  tests/e2e/e2e_test.go
Labels: approved, lgtm, ok-to-test

#692 Restart profileparser on failures
  cmd/manager/profileparser.go
  pkg/profileparser/profileparser.go
  tests/e2e/e2e_test.go
Labels: approved, lgtm

#699 Disallow empty titles and descriptions for tailored profiles
  deploy/crds/compliance.openshift.io_tailoredprofiles_crd.yaml
  pkg/apis/compliance/v1alpha1/tailoredprofile_types.go
  pkg/xccdf/tailoring.go
Labels: approved, lgtm

#698 Remove Variable Selection check for tailor profile
  pkg/apis/compliance/v1alpha1/variable_test.go
  pkg/apis/compliance/v1alpha1/variable_types.go
Labels: approved, lgtm, ok-to-test

#701 Release v0.1.40
  CHANGELOG.md
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_compliancecheckresults_crd.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_compliancescans_crd.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_compliancesuites_crd.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_scansettings_crd.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_tailoredprofiles_crd.yaml
  version/version.go
Labels: approved

#694 Bug 1999374: Use ClusterRole/ClusterRoleBinding for monitoring permissions
  Makefile
  README.md
  deploy/olm-catalog/compliance-operator/manifests/monitoring_clusterrole.yaml
  deploy/olm-catalog/compliance-operator/manifests/monitoring_clusterrolebinding.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-medium

#705 Makefile: Rename IMAGE_FORMAT var
  Makefile
Labels: approved, lgtm

#706 e2e: Mark logging functions as helper functions
  tests/e2e/helpers.go
Labels: approved, lgtm

#707 Fetch openscap version during build
  images/openscap/Dockerfile
  images/openscap/Dockerfile.ci
  images/openscap/jhrozek-openscap-1.3.4-epel-8.repo
  pkg/controller/compliancescan/config.go
Labels: approved, lgtm, ok-to-test

#703 Add instructions and check type to Rule object
  deploy/crds/compliance.openshift.io_rules_crd.yaml
  doc/crds.md
  pkg/apis/compliance/v1alpha1/rule_types.go
  pkg/profileparser/profileparser.go
  pkg/profileparser/profileparser_test.go
  pkg/utils/parse_arf_result.go
  tests/e2e/e2e_test.go
Labels: approved, lgtm

#711 Add flag to skip the metrics deployment
  cmd/manager/operator.go
Labels: approved, lgtm

#709 Specify fsgroup, user and non-root user usage in resultserver
  deploy/role.yaml
  pkg/controller/compliancescan/compliancescan_controller_test.go
  pkg/controller/compliancescan/resultserver.go
Labels: approved, lgtm

#710 Gather /version when doing Platform scans
  cmd/manager/scap.go
Labels: approved

#712 Release v0.1.41
  CHANGELOG.md
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_rules_crd.yaml
  version/version.go
Labels: approved

#713 Add description to TailoredProfile yaml
  doc/tutorials/workshop/content/exercises/05-tailoring-profiles.md
Labels: approved, lgtm, ok-to-test

#717 Remove Benchmark unit tests
  pkg/profileparser/profileparser_test.go
  pkg/utils/parse_arf_result_test.go
Labels: approved, lgtm

#718 Update 06-troubleshooting.md - small fix in log filtering
  doc/tutorials/workshop/content/exercises/06-troubleshooting.md
Labels: approved, lgtm, ok-to-test

#716 Validate that rules in tailored profile are of appropriate type
  deploy/crds/compliance.openshift.io_tailoredprofiles_crd.yaml
  pkg/apis/compliance/v1alpha1/tailoredprofile_types.go
  pkg/controller/tailoredprofile/tailoredprofile_controller.go
  pkg/controller/tailoredprofile/tailoredprofile_controller_test.go
Labels: approved, lgtm

#702 Modify openscap build in Makefile
  Makefile
  deploy/operator.yaml
Labels: approved, lgtm, ok-to-test

#715 aggregator: Remove MachineConfig validation
  cmd/manager/aggregator.go
Labels: approved, lgtm

#719 Fix needs-review unpause pool
  pkg/controller/compliancesuite/compliancesuite_controller.go
Labels: approved, lgtm, ok-to-test

#714 Proposal for Kubelet Config Remediation
  doc/kubeletConfig-remediations.md
Labels: approved, lgtm, ok-to-test

#720 Makefile: Add push-openscap-image target
  Makefile
Labels: approved, lgtm

#723 docs: Document the default-auto-apply ScanSetting
  doc/crds.md
  doc/remediation-flow.md
  doc/troubleshooting.md
Labels: approved, lgtm

#721 add error to the result object as comment
  cmd/manager/scap.go
  cmd/manager/scap_test.go
Labels: approved, tide/merge-method-squash, lgtm
