Repository openshift/compliance-operator, pull requests merged in 2021-02, with the labels that each got.

#553 Backport v0.1.25 to 4.6
  Makefile
  README.md
  cmd/manager/operator.go
  cmd/manager/resultcollector.go
  cmd/manager/resultcollector_test.go
  deploy/crds/compliance.openshift.io_tailoredprofiles_crd.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_tailoredprofiles_crd.yaml
  doc/troubleshooting.md
  pkg/apis/compliance/v1alpha1/complianceremediation_types.go
  pkg/apis/compliance/v1alpha1/compliancescan_types.go
  pkg/apis/compliance/v1alpha1/compliancesuite_types.go
  pkg/apis/compliance/v1alpha1/tailoredprofile_types.go
  pkg/controller/complianceremediation/complianceremediation_controller.go
  pkg/controller/complianceremediation/complianceremediation_controller_test.go
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/compliancescan_controller_test.go
  pkg/controller/compliancescan/scan.go
  pkg/controller/compliancescan/scantype.go
  pkg/controller/compliancesuite/compliancesuite_controller.go
  pkg/controller/compliancesuite/compliancesuite_controller_test.go
  pkg/controller/compliancesuite/compliancesuite_suite_test.go
  pkg/controller/scansettingbinding/scansettingbinding_controller_test.go
  pkg/controller/tailoredprofile/tailoredprofile_controller.go
  pkg/profileparser/profileparser.go
  pkg/profileparser/profileparser_suite_test.go
  pkg/profileparser/profileparser_test.go
  pkg/utils/images.go
Labels: approved

#557 Add Disconnected support annotation to CSV
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#558 Release v0.1.26
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
Labels: approved

#562 Output relevant object in warnings
  cmd/manager/scap.go
Labels: approved, lgtm

#559 Backport v0.1.26
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
Labels: approved

#560 Backport v0.1.26
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
Labels: approved

#561 api: Set the SuiteLabel correctly
  pkg/apis/compliance/v1alpha1/complianceremediation_types.go
Labels: approved, lgtm

#563 doc: Update our documentation with respect to the latest changes
  README.md
  doc/crds.md
  doc/troubleshooting.md
Labels: approved, lgtm

#564 Backport fixes
  cmd/manager/scap.go
  pkg/apis/compliance/v1alpha1/complianceremediation_types.go
Labels: approved

#565 Backport fixes
  cmd/manager/scap.go
  pkg/apis/compliance/v1alpha1/complianceremediation_types.go
Labels: approved

#568 Add an explicit MANUAL compliancecheck result status
  doc/crds.md
  pkg/apis/compliance/v1alpha1/compliancecheckresult_types.go
  pkg/utils/parse_arf_result.go
  tests/e2e/e2e_test.go
Labels: approved, lgtm

#567 api: Surface a new attribute instructions that contains OCIL
  deploy/crds/compliance.openshift.io_compliancecheckresults_crd.yaml
  doc/crds.md
  pkg/apis/compliance/v1alpha1/compliancecheckresult_types.go
  pkg/utils/parse_arf_result.go
  pkg/utils/parse_arf_result_test.go
Labels: approved, lgtm

#570 Enable OCP-provided monitoring services
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#571 Update container registry to registry.ci.openshift.org
  Dockerfile.ci
  Dockerfile.ocp
  images/openscap/Dockerfile.ci
Labels: approved, lgtm

#572 Label ComplianceCheck CRs that have automated remediations
  cmd/manager/aggregator.go
  doc/crds.md
  pkg/apis/compliance/v1alpha1/compliancecheckresult_types.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm

#574 operator: Remove dead function profileBundlesDiffer
  cmd/manager/operator.go
Labels: approved, lgtm

#573 Bug 1919311: Use a separate SA for resultserver
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  pkg/controller/compliancescan/resultserver.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, qe-approved

#575 Add dependency handling for remediations
  cmd/manager/aggregator.go
  cmd/manager/operator.go
  doc/remediation-flow.md
  pkg/apis/compliance/v1alpha1/complianceremediation_types.go
  pkg/controller/complianceremediation/complianceremediation_controller.go
  pkg/controller/complianceremediation/complianceremediation_controller_test.go
  pkg/utils/parse_arf_result.go
Labels: approved, lgtm

#576 Fix profileparser race condition
  pkg/profileparser/profileparser_test.go
Labels: approved, lgtm

#578 Release v0.1.27
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_compliancecheckresults_crd.yaml
Labels: approved, lgtm

#580 Release v0.1.27
  Dockerfile.ci
  Dockerfile.ocp
  README.md
  cmd/manager/aggregator.go
  cmd/manager/operator.go
  deploy/crds/compliance.openshift.io_compliancecheckresults_crd.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_compliancecheckresults_crd.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  doc/crds.md
  doc/remediation-flow.md
  doc/troubleshooting.md
  images/openscap/Dockerfile.ci
  pkg/apis/compliance/v1alpha1/compliancecheckresult_types.go
  pkg/apis/compliance/v1alpha1/complianceremediation_types.go
  pkg/controller/complianceremediation/complianceremediation_controller.go
  pkg/controller/complianceremediation/complianceremediation_controller_test.go
  pkg/controller/compliancescan/resultserver.go
  pkg/profileparser/profileparser_test.go
  pkg/utils/parse_arf_result.go
  pkg/utils/parse_arf_result_test.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm

#582 Release v0.1.27
  Dockerfile.ci
  Dockerfile.ocp
  README.md
  cmd/manager/aggregator.go
  cmd/manager/operator.go
  deploy/crds/compliance.openshift.io_compliancecheckresults_crd.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_compliancecheckresults_crd.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  doc/crds.md
  doc/remediation-flow.md
  doc/troubleshooting.md
  images/openscap/Dockerfile.ci
  pkg/apis/compliance/v1alpha1/compliancecheckresult_types.go
  pkg/apis/compliance/v1alpha1/complianceremediation_types.go
  pkg/controller/complianceremediation/complianceremediation_controller.go
  pkg/controller/complianceremediation/complianceremediation_controller_test.go
  pkg/controller/compliancescan/resultserver.go
  pkg/profileparser/profileparser_test.go
  pkg/utils/parse_arf_result.go
  pkg/utils/parse_arf_result_test.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm

#581 Release v0.1.27
  Dockerfile.ci
  Dockerfile.ocp
  README.md
  cmd/manager/aggregator.go
  cmd/manager/operator.go
  deploy/crds/compliance.openshift.io_compliancecheckresults_crd.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_compliancecheckresults_crd.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  doc/crds.md
  doc/remediation-flow.md
  doc/troubleshooting.md
  images/openscap/Dockerfile.ci
  pkg/apis/compliance/v1alpha1/compliancecheckresult_types.go
  pkg/apis/compliance/v1alpha1/complianceremediation_types.go
  pkg/controller/complianceremediation/complianceremediation_controller.go
  pkg/controller/complianceremediation/complianceremediation_controller_test.go
  pkg/controller/compliancescan/resultserver.go
  pkg/profileparser/profileparser_test.go
  pkg/utils/parse_arf_result.go
  pkg/utils/parse_arf_result_test.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm

#579 Bug 1920577: Rename the SKIP state of ComplianceCheckResult to NOT-APPLICABLE
  doc/crds.md
  pkg/apis/compliance/v1alpha1/compliancecheckresult_types.go
  pkg/utils/parse_arf_result.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
