Repository openshift/compliance-operator, pull requests merged in 2021-08, with the labels that each got.

#676 Bug 1946512: Use latest for CSV documentation link
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug

#677 Add a must-gather plugin
  Makefile
  README.md
  images/must-gather/Dockerfile
  utils/must-gather/gather
  utils/must-gather/gather_compliance
Labels: approved

#678 Release v0.1.37
  CHANGELOG.md
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_complianceremediations_crd.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_compliancescans_crd.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_compliancesuites_crd.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_scansettings_crd.yaml
  version/version.go
Labels: approved

#679 Add fetch-git-tags make target
  Makefile
Labels: approved

#680 Bug 1990836: Move metrics service creation back into operator startup
  cmd/manager/operator.go
  deploy/operator.yaml
  deploy/service_account.yaml
  tests/e2e/e2e_test.go
Labels: approved

#681 Release v0.1.38
  CHANGELOG.md
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm

#682 Update wording in TailoredProfile CRD
  deploy/crds/compliance.openshift.io_tailoredprofiles_crd.yaml
Labels: approved, lgtm, ok-to-test

#683 Print Compliance Operator version on startup
  cmd/manager/operator.go
Labels: approved, lgtm

#685 Allow profileparser to parse PCI-DSS references
  pkg/profileparser/profileparser.go
Labels: approved, lgtm

#684 Add permission for operator to remediate prometheusrule objects
  deploy/role.yaml
Labels: approved

#686 Release v0.1.39
  CHANGELOG.md
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_tailoredprofiles_crd.yaml
  version/version.go
Labels: approved, lgtm

#688 Bug 1969620: compliancescan: Fill the <target> element and the urn:xccdf:fact:identifier for node checks
  pkg/controller/compliancescan/config.go
  pkg/controller/compliancescan/scan.go
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low
