Repository openshift/compliance-operator, pull requests merged in 2021-01, with the labels that each got.

#536 Release v0.1.24
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
Labels: approved

#541 Refactor and test code that waits for "result" file
  cmd/manager/resultcollector.go
  cmd/manager/resultcollector_test.go
Labels: approved, lgtm

#540 profileparser: parallelize rule and variable parsing
  pkg/profileparser/profileparser.go
  pkg/profileparser/profileparser_suite_test.go
  pkg/profileparser/profileparser_test.go
Labels: approved, lgtm

#539 Remove outputType logic from TailoredProfile
  deploy/crds/compliance.openshift.io_tailoredprofiles_crd.yaml
  pkg/apis/compliance/v1alpha1/tailoredprofile_types.go
  pkg/controller/scansettingbinding/scansettingbinding_controller_test.go
  pkg/controller/tailoredprofile/tailoredprofile_controller.go
Labels: approved, lgtm

#544 Fix init container content defaulting for OCP builds
  cmd/manager/operator.go
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/utils/images.go
Labels: approved, lgtm

#547 Add clarification about supported OpenShift version
  README.md
Labels: approved, lgtm

#546 Bug 1919098: Add annotations to better deal with remediations
  doc/troubleshooting.md
  pkg/apis/compliance/v1alpha1/complianceremediation_types.go
  pkg/apis/compliance/v1alpha1/compliancesuite_types.go
  pkg/controller/complianceremediation/complianceremediation_controller.go
  pkg/controller/complianceremediation/complianceremediation_controller_test.go
  pkg/controller/compliancesuite/compliancesuite_controller.go
  pkg/controller/compliancesuite/compliancesuite_controller_test.go
  pkg/controller/compliancesuite/compliancesuite_suite_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#548 Don't build binary with `-race` flag
  Makefile
Labels: approved, lgtm

#543 refactor: Introduce scan type handler
  pkg/apis/compliance/v1alpha1/compliancescan_types.go
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/compliancescan_controller_test.go
  pkg/controller/compliancescan/scan.go
  pkg/controller/compliancescan/scantype.go
Labels: approved, lgtm

#549 Release v0.1.25
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_tailoredprofiles_crd.yaml
Labels: approved, lgtm

#554 Backport v0.1.25 to 4.6
  Makefile
  README.md
  cmd/manager/operator.go
  cmd/manager/resultcollector.go
  cmd/manager/resultcollector_test.go
  deploy/crds/compliance.openshift.io_tailoredprofiles_crd.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_tailoredprofiles_crd.yaml
  doc/troubleshooting.md
  pkg/apis/compliance/v1alpha1/complianceremediation_types.go
  pkg/apis/compliance/v1alpha1/compliancescan_types.go
  pkg/apis/compliance/v1alpha1/compliancesuite_types.go
  pkg/apis/compliance/v1alpha1/tailoredprofile_types.go
  pkg/controller/complianceremediation/complianceremediation_controller.go
  pkg/controller/complianceremediation/complianceremediation_controller_test.go
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/compliancescan_controller_test.go
  pkg/controller/compliancescan/scan.go
  pkg/controller/compliancescan/scantype.go
  pkg/controller/compliancesuite/compliancesuite_controller.go
  pkg/controller/compliancesuite/compliancesuite_controller_test.go
  pkg/controller/compliancesuite/compliancesuite_suite_test.go
  pkg/controller/scansettingbinding/scansettingbinding_controller_test.go
  pkg/controller/tailoredprofile/tailoredprofile_controller.go
  pkg/profileparser/profileparser.go
  pkg/profileparser/profileparser_suite_test.go
  pkg/profileparser/profileparser_test.go
  pkg/utils/images.go
Labels: approved, lgtm
