Repository openshift/compliance-operator, pull requests merged in 2021-06, with the labels that each got.

#650 Remove unused const definitions
  pkg/utils/parse_arf_result.go
Labels: approved, lgtm

#651 Release v0.1.34
  CHANGELOG.md
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#653 RBAC: Add permissions to update oauths config
  deploy/role.yaml
Labels: approved, lgtm

#655 Release v0.1.35
  CHANGELOG.md
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm

#656 docs: Add an example of setting a variable in a tailoredProfile
  doc/crds.md
Labels: approved, lgtm

#659 TP: When transitioning to Ready, remove previous error message
  pkg/controller/tailoredprofile/tailoredprofile_controller.go
  pkg/controller/tailoredprofile/tailoredprofile_controller_test.go
Labels: approved, lgtm

#660 Bug 1975358: Refresh pool reference before trying to unpause it
  pkg/controller/compliancesuite/compliancesuite_controller.go
  pkg/controller/compliancesuite/compliancesuite_controller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#662 Issue warning if filter issues more than one object
  cmd/manager/scap.go
  cmd/manager/scap_test.go
Labels: approved, lgtm

#661 This fixes the issue where a empty remediation yaml file is present
  cmd/manager/aggregator.go
  cmd/manager/aggregator_test.go
Labels: approved, lgtm, ok-to-test

#663 Release v0.1.36
  CHANGELOG.md
  Makefile
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm
