Repository openshift/compliance-operator, pull requests merged in 2021-07, with the labels that each got.

#664 Move Compliance Operator to use ubi-micro
  Dockerfile.ci
  Dockerfile.ocp
  build/Dockerfile
Labels: approved, lgtm

#666 tailoring: Update the tailoring CM on changes
  pkg/controller/tailoredprofile/tailoredprofile_controller.go
  pkg/controller/tailoredprofile/tailoredprofile_controller_test.go
Labels: approved, lgtm

#652 Add implementation of enforcement remediations
  cmd/manager/aggregator.go
  cmd/manager/aggregator_test.go
  deploy/crds/compliance.openshift.io_complianceremediations_crd.yaml
  deploy/crds/compliance.openshift.io_compliancescans_crd.yaml
  deploy/crds/compliance.openshift.io_compliancesuites_crd.yaml
  deploy/crds/compliance.openshift.io_scansettings_crd.yaml
  deploy/role.yaml
  doc/enforcement-remediations.md
  pkg/apis/compliance/v1alpha1/complianceremediation_types.go
  pkg/apis/compliance/v1alpha1/complianceremediation_types_test.go
  pkg/apis/compliance/v1alpha1/compliancescan_types.go
  pkg/apis/compliance/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/complianceremediation/complianceremediation_controller.go
  pkg/controller/complianceremediation/complianceremediation_controller_test.go
  pkg/profileparser/profileparser.go
  pkg/utils/objparser.go
  pkg/utils/objparser_test.go
  pkg/utils/parse_arf_result.go
  pkg/utils/parse_arf_result_test.go
  pkg/utils/remediation_diff.go
  pkg/utils/remediation_diff_test.go
Labels: approved, lgtm

#665 The remediation templating design document
  doc/remediation-templating.md
Labels: approved, ok-to-test

#667 Add NERC-CIP reference support
  pkg/profileparser/profileparser.go
Labels: approved, lgtm

#668 Fix instructions on building VMs
  doc/tutorials/workshop/content/exercises/07-content-setup.md
Labels: approved, lgtm, needs-ok-to-test

#669 Bump the suitererunner resource limits
  pkg/controller/compliancesuite/suitererunner.go
Labels: approved, lgtm

#673 adding CI tests for controller metrics
  deploy/service_account.yaml
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm

#674 doc: note that rolling back images in ProfileBundle is not well supported
  doc/crds.md
Labels: approved, lgtm
