Repository openshift/compliance-operator, pull requests merged in 2022-01, with the labels that each got.

#769 Use consistent markdown headings in README.md
  README.md
Labels: approved, lgtm

#770 Add conventions for writing release notes
  README.md
Labels: approved, lgtm

#766 Add a more verbose changelog for 0.1.47
  CHANGELOG.md
Labels: approved, lgtm

#772 Update the TailoredProfile example to include a description
  deploy/crds/compliance.openshift.io_v1alpha1_tailoredprofile_cr.yaml
Labels: approved

#775 Bug 2040401: fix can't find owner of 98-<pool>-generated-kubelet
  pkg/controller/complianceremediation/complianceremediation_controller.go
  pkg/controller/complianceremediation/complianceremediation_controller_test.go
  pkg/utils/nodeutils.go
  pkg/utils/nodeutils_test.go
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high

#776 Render list properly in tutorial documentation
  doc/tutorials/workshop/content/exercises/03-creating-your-first-scan.md
Labels: approved, lgtm

#771 Introduce process documentation for maintaining release notes
  CHANGELOG.md
  README.md
  utils/update_changelog.sh
Labels: approved, lgtm

#777 Add release notes for v0.1.48
  CHANGELOG.md
Labels: approved, lgtm

#778 Make sure the helm chart.yaml changes are included in release commit
  Makefile
Labels: approved, lgtm

#780 Release v0.1.48
  CHANGELOG.md
  deploy/compliance-operator-chart/Chart.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_compliancescans_crd.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_compliancesuites_crd.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance.openshift.io_scansettings_crd.yaml
  version/version.go
Labels: approved
