Repository openshift/compliance-operator, pull requests merged in 2022-02, with the labels that each got.

#782 Add Lance to OWNERS
  OWNERS
Labels: approved

#786 Break the release process apart
  CHANGELOG.md
  Makefile
  README.md
Labels: approved, lgtm

#789 Address follow-up comments to PR 786
  CHANGELOG.md
  Makefile
  README.md
Labels: approved, lgtm

#784 Add status descriptors back into CSV
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#787 Remove the deploy/eks.yaml deployment
  CHANGELOG.md
  deploy/eks.yaml
Labels: approved, lgtm

#785 Add network to api-resources we always fetch
  cmd/manager/scap.go
Labels: approved, lgtm

#790 e2e: Don't rely on order of inconsistent results
  CHANGELOG.md
  tests/e2e/e2e_test.go
Labels: approved, lgtm

#794 Update build_ds_container.sh script in tutorials
  doc/tutorials/workshop/content/exercises/07-content-setup.md
  doc/tutorials/workshop/content/exercises/08-creating-profile-bundles.md
Labels: approved, lgtm

#792 Reconcile ScanSettingBindings when a TailoredProfile changes
  CHANGELOG.md
  pkg/controller/scansettingbinding/scansettingbinding_controller.go
  pkg/controller/scansettingbinding/tailored_profile_mapper.go
  pkg/controller/tailoredprofile/tailoredprofile_controller.go
  pkg/controller/tailoredprofile/tailoredprofile_controller_test.go
  tests/e2e/e2e_test.go
Labels: approved, lgtm

#795 Other arch images
  Makefile
Labels: approved, lgtm, ok-to-test

#768 Add labels to indicate availability for other arches
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#793 Update changelog for previous PRs
  CHANGELOG.md
Labels: approved, lgtm

#798 e2e: Fix TestInconsistentResult
  tests/e2e/e2e_test.go
Labels: approved, needs-ok-to-test, lgtm
