Repository openshift/compliance-operator, pull requests merged in 2022-04, with the labels that each got.

#816 Added permission for api-resource-collector
  CHANGELOG.md
  deploy/role.yaml
Labels: approved, lgtm

#815 Modify the api-resource-collector to fetch network operator resources
  CHANGELOG.md
  deploy/role.yaml
Labels: approved, lgtm

#812 Updated v0.1.49 changelog broken URL
  CHANGELOG.md
Labels: approved, needs-ok-to-test, lgtm

#819 Update api-resource-collector cluster role to check if GitOps operator is installed
  CHANGELOG.md
  deploy/role.yaml
Labels: approved, lgtm

#818 Fetch node resources
  CHANGELOG.md
  cmd/manager/scap.go
Labels: approved, lgtm

#817 e2e: Only check for the coreos-vsyscall-kernel-argument on x86
  tests/e2e/e2e_test.go
Labels: approved, lgtm

#821 Use Quay compliance-operator/compliance-operator-content for content …
  CHANGELOG.md
  Makefile
  deploy/compliance-operator-chart/templates/deployment.yaml
  deploy/crds/compliance.openshift.io_v1alpha1_compliancesuite_cr.yaml
  deploy/crds/compliance.openshift.io_v1alpha1_profilebundle_cr.yaml
  deploy/olm-catalog/compliance-operator/manifests/compliance-operator.clusterserviceversion.yaml
  deploy/operator.yaml
  doc/crds.md
  doc/tutorials/workshop/content/exercises/03-creating-your-first-scan.md
  images/testcontent/Dockerfile.ci
  pkg/controller/compliancescan/utils.go
  pkg/controller/scansettingbinding/scansettingbinding_controller_test.go
  pkg/utils/images.go
Labels: approved, lgtm

#814 BUG 2071854: Fix unpausing machine config pool too soon
  CHANGELOG.md
  go.mod
  go.sum
  pkg/controller/complianceremediation/complianceremediation_controller.go
  pkg/controller/compliancesuite/compliancesuite_controller.go
  pkg/controller/compliancesuite/compliancesuite_controller_test.go
  pkg/utils/compare_json.go
  pkg/utils/nodeutils.go
  vendor/github.com/PaesslerAG/gval/.gitignore
  vendor/github.com/PaesslerAG/gval/.travis.yml
  vendor/github.com/PaesslerAG/gval/LICENSE
  vendor/github.com/PaesslerAG/gval/README.md
  vendor/github.com/PaesslerAG/gval/evaluable.go
  vendor/github.com/PaesslerAG/gval/functions.go
  vendor/github.com/PaesslerAG/gval/go.mod
  vendor/github.com/PaesslerAG/gval/go.sum
  vendor/github.com/PaesslerAG/gval/gval.go
  vendor/github.com/PaesslerAG/gval/language.go
  vendor/github.com/PaesslerAG/gval/operator.go
  vendor/github.com/PaesslerAG/gval/parse.go
  vendor/github.com/PaesslerAG/gval/parser.go
  vendor/github.com/PaesslerAG/gval/prtg-batmin-gopher.png
  vendor/github.com/PaesslerAG/jsonpath/.gitignore
  vendor/github.com/PaesslerAG/jsonpath/.travis.yml
  vendor/github.com/PaesslerAG/jsonpath/LICENSE
  vendor/github.com/PaesslerAG/jsonpath/README.md
  vendor/github.com/PaesslerAG/jsonpath/go.mod
  vendor/github.com/PaesslerAG/jsonpath/go.sum
  vendor/github.com/PaesslerAG/jsonpath/jsonpath.go
  vendor/github.com/PaesslerAG/jsonpath/parse.go
  vendor/github.com/PaesslerAG/jsonpath/path.go
  vendor/github.com/PaesslerAG/jsonpath/placeholder.go
  vendor/github.com/PaesslerAG/jsonpath/selector.go
  vendor/github.com/PaesslerAG/jsonpath/test.sh
  vendor/modules.txt
Labels: do-not-merge/hold, approved, bugzilla/valid-bug, lgtm, bugzilla/severity-medium

#822 Fix memory pointer crash loop
  CHANGELOG.md
  pkg/utils/nodeutils.go
  pkg/utils/nodeutils_test.go
  tests/e2e/constants.go
  tests/e2e/e2e_test.go
  tests/e2e/helpers.go
Labels: approved, lgtm

#824 Add contributor documentation for running unit and e2e tests
  doc/contributor.md
Labels: approved, lgtm

#820 Bug 2075029: scans: Delete scan pods and aggregator when they're done
  CHANGELOG.md
  pkg/controller/compliancescan/aggregator.go
  pkg/controller/compliancescan/compliancescan_controller.go
  pkg/controller/compliancescan/compliancescan_controller_test.go
  pkg/controller/compliancescan/scantype.go
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-high
